### ISSUE TITLE
expandPic failing when expanding virtual decimals

### ISSUE THREAD

**Issue by labiraus** [AbsaOSS/cobrix#102]
If a .cob file has a pic with two sets of braces in it, if either set of braces has more than one digit in it then the parser fails to parse that line and returns an error NOT DIVISIBLE by the RECORD SIZE calculated from the copybook with a byte count less than what should be expected.

Pass: PIC S9(15)V99.
Pass: PIC S9(9)V9(6).
Fail: S9(15)V9(2).

I suspect that this may be something to do with repeatCount in expandPic on line 944 of CopybookParser.scala

**Comment by yruslan** [comment]
Thanks for the bug report. Unable to reproduce in on the current master though. What version of Cobrix are you using?

Added tests to cover these specific cases. Take a look at [this commit (5b1338153)](https://github.com/AbsaOSS/cobrix/commit/5b1338153bfbe9e9cd6fa07fb94f8ec59a9341f7).
For `S9(15)V99` and `S9(15)V9(2)` the parser produced the same field size (17). The scale and precision are the same as well.

If this is still an issue in the current master, could you please provide the part of the copybook where that happens and parts of layout positions showing the difference of field lengths which should be printed to the log.

**Comment by yruslan** [comment]
Please, check if this is still an issue in `0.5.1`.
