### ISSUE TITLE
signed decimal places

### ISSUE THREAD

**Issue by KubayV** [AbsaOSS/cobrix#103]
Hi, 
I have fields which are made up of 7 numeric digits   S9(7). We need them to have 7 decimal places and I cannot find a PIC that can achieve that. 
So a value of 000456J needs to become -0.0004561
V9(7) achieves that, but only for positive values, it brings nulls for negatives.
I've tried several PICS including a few below, but they either fail, or do not achieve desirable result:
SV9(7)
S9(0)V9(7)
Can you please let me know what PIC I need to use to achieve 7 decimal places for signed field of 7 digits?
Thank you

**Comment by yruslan** [comment]
Thanks for raising the issue. It seems like you have a trailing non-separate sign which is not supported in Cobrix yet. `SV9(7)` is for numbers like `A004561` (the sign is in the most significant/leading digit).

Will add support for this PIC:
`PIC SV9(7) SIGN IS TRAILING.`

**Comment by yruslan** [comment]
Double checked the implementation. Both leading and trailing punched signs should be supported, even if not explicitly specified. So `SV9(7)` should work in your case. Will add a test for this.

A couple of additional questions to you:
- What is the exact field definition (including 'DISPLAY' and other keywords)?
- Could you elaborate on what kind of the wrong behavior you see when using `SV9(7)`?

**Comment by KubayV** [comment]
Hi, I got the latest version of your library and SV9(7) worked for both +ve and -ve values. Thank you!

**Comment by yruslan** [comment]
You are welcome. Great it worked for you.
