### ISSUE TITLE
How to clean special characters in binary file before sending the file to cobrix parser

### ISSUE THREAD

**Issue by geethab123** [AbsaOSS/cobrix#119]
I had some special characters in the middle of the record like line feed or new line, carriage return, double quotes etc in my mainframe binary file. Is there a way that we can replace these characters with spaces

**Comment by yruslan** [comment]
Conrix retains all characters as much as possible so by default line endings are retained. But I think you can achieve the cleanup you require using custom code pages.

Currently Cobrix supports the following built-in code pages: `common` (default), `common_extended`, `cp037`, `cp037_extended`. The '*_extended' pages include characters that only supported by UNICODE.

In addition to the built-in code pages there is a feature allowing you to provide your own implementation using this option:
```
.option("ebcdic_code_page_class", "full.class.specifier")
```

You can create a custom code page table similar to [this example.](https://github.com/AbsaOSS/cobrix/blob/master/spark-cobol/src/test/scala/za/co/absa/cobrix/spark/cobol/source/utils/CustomCodePage.scala)

You can map unneeded characters to spaces in your custom table. Then, you need to pass your class name to the above option.

**Comment by geethab123** [comment]
Thank you for your reply. I will check according to your comments.   I am not interested to remove line ending at the end. I am concerned about the special characters in the middle. because of which one record is considered as multiple records while parsing. I would like to avoid that so I need to remove those characters in the middle of the records.

**Comment by yruslan** [comment]
Cobrix works with binary files. Special characters anywhere in the data file should not affect splitting of a file by records. Each file is split either by record size of a record's layout, or by RDW headers. Not sure how changing line end characters in the middle splits records. Could you please describe an example?

**Comment by geethab123** [comment]
we have parsed the variable length file with record length field option. When I displayed the records below is the output.
![image](https://user-images.githubusercontent.com/17115429/60902920-0c4fc980-a236-11e9-8a01-cf3c7cfcc5fd.png)

**Comment by yruslan** [comment]
The records look fine. The line breaks are just a displaying artefacts only.
Try `df.toJSON.take(100).foreach(println)`
