### ISSUE TITLE
Copybook that describes a VARCHAR field of a table and Cobrix extracts the length but not the text

### ISSUE THREAD

**Issue by rafajimenez72** [AbsaOSS/cobrix#136]
We have a copybook with a field that represents a VARCHAR of a table in the following way:
* VARCHAR DATA TYPE
     10 COL8.
          49 COL8-LEN PIC S9 (4) USAGE COMP.
          49 COL8-TEXT PIC X (1000).		

- In the EBCDIC file there are no records with the maximum text size and cobrix only extracts the length field but not the text.
- It is necessary to cobrix that there is a record with the maximum size to work correctly.

- I've also done tests to change the definition of the copybook by putting the smaller text size and then cobrix truncates those larger records but works at least.
- I've tried two different copybooks and files and the results are the same

Thanks in advance

**Comment by yruslan** [comment]
Seems like an interesting use case. Could you please answer a couple of additional questions.
- Do I understand correctly that your copybooks contain many fields, and only one of them is VARCHAR?
- Is that field always last or a VARCHAR field can be in the middle so there are other fields that are located before and after the VARCHAR field?
- Is there is any format (in COBOL) indication that the field has a variable size?
- Is there any field or a record header that stores a total record size for each record?

Depending on the answers a workaround may be possible. I'm trying to determine it such files can be loaded using current Cobrix capabilities.

**Comment by rafajimenez72** [comment]
Hi,

- Yes, the copybooks contain many fields and the last one represents a VARCHAR
- For now, the examples we have is always the field at the end and there is only one VARCHAR field
- The EBCDIC file is of variable length and includes the big-endian RDW field for each record
- The RDW field is compliant with the characteristic "is_rdw_part_of_record_length"
- We are creating the DataFrame with the following options:
    val df = spark
      .read
      .format("cobol")
      .option("copybook", "/path/copybook")   
      .option("schema_retention_policy", "collapse_root")
      .option("is_record_sequence", "true")
      .option("is_rdw_big_endian", "true")
      .option("is_rdw_part_of_record_length", true)
      .load("/path/EBCDIC.file")

Thanks in advance

**Comment by yruslan** [comment]
I think it is not hard to add support for your use case.

Currently a field is only extracted if the number of bytes available completely matches the size of the field. But for a string field it makes sense to extract a string even if the number of bytes available are less than the field size.

Adding this to the backlog.

**Comment by rafajimenez72** [comment]
A lot of thanks.

**Comment by rafajimenez72** [comment]
Hi,

We have several files with this use case
When do you estimate that you could incorporate this feature into cobrix?, It's very interesting for us.
Is there any trick in the meantime?

Thanks in advance

**Comment by yruslan** [comment]
I see. Will prioritize that. Looks quite easy to implement. Expect the feature to be available sometime next week.
Have a nice weekend!

**Comment by yruslan** [comment]
It seems the issue is simpler than I thought. You can test the initial implementation using the current snapshot:
```xml
<dependency>
      <groupId>za.co.absa.cobrix</groupId>
      <artifactId>spark-cobol</artifactId>
      <version>0.5.5-SNAPSHOT</version>
</dependency>
```
or you can clone the dev branch: `feature/136-add-support-varchar-field`

**Comment by rafajimenez72** [comment]
Hi,
On Monday, I will try the files and let you know.
A lot of thanks.

**Comment by rafajimenez72** [comment]
Hi,
I downloaded the branch and generated 0.5.5-SNAPSHOT
The results have been good, 
The "text" field appears in the DataFrame

A lot of thanks
