### ISSUE TITLE
 Generate an EBCDIC file.

### ISSUE THREAD

**Issue by rafajimenez72** [AbsaOSS/cobrix#139]
Hello,
I have a question
Does it make sense to cobrix to incorporate a feature that allows starting from a dataframe to generate an EBCDIC file using a CopyBook?
Thanks in advance

**Comment by yruslan** [comment]
Yes, it makes sense. But it is not currently in our plans.
1. We don't have a use case for this.
2. We still have a lot of thing to implement for the mainframe reader. Implementing a writer seems like a double effort.

But contributions are always welcome. :smiley:

**Comment by rafajimenez72** [comment]
Yes, thank you, I understand.
It is a very interesting project
