### ISSUE TITLE
Does Cobrix support Google Cloud Storage (gs://) ?

### ISSUE THREAD

**Issue by yparesh** [AbsaOSS/cobrix#150]
Does Cobrix support Google Cloud Storage (gs://) ?

**Comment by yruslan** [comment]
Not at the moment. Maybe sometime in the future. Currently, Cobrix supports only HDFS.

**Comment by yparesh** [comment]
Thank you Ruslan for clarifying.

**Comment by yruslan** [comment]
Cobrix 2.2.0 is released. It supports S3 now. But the solution is generic and Cobrix should be able to support any connectors supported by Spark.

Please, let me know if it works for you. If there are issues, we can take a look.

**Comment by yparesh** [comment]
This is great news! Thanks for adding this feature!!

Thanks
Paresh
