### ISSUE TITLE
Occurs depending on mappings

### ISSUE THREAD

**Issue by tr11** [AbsaOSS/cobrix#151]
I have a few copybooks that have groups occurring depending on a flag on some field as follows:

```
   02 FIELD_TYPE                  PIC X.
   02 RECORD_TYPE_A OCCURS 0 TO 1 TIMES DEPENDING ON FIELD_TYPE.
       ....
   02 RECORD_TYPE_B OCCURS 0 TO 1 TIMES DEPENDING ON FIELD_TYPE.
       ....
```

In this example, if `FIELD_TYPE` is `A`, then only `RECORD_TYPE_A` is defined. Same for `B`.

Maybe we could support something like this by allowing `OCCURS` clauses to point to non-integer fields together with some sort of mapping.
If this sounds good, I can come up with a PR that does this.

**Comment by yruslan** [comment]
Yes, this makes sense overall. But how a mapping can be defined? Is it a part of the copybook or need to be specified via `.option(...)`?

**Comment by tr11** [comment]
It would have to be done through an option.  I'm not sure if this is standard at all, but the files I have are structured this way.

**Comment by yruslan** [comment]
Makes sense. Could you please give an example of such a mapping? Can it be several mappings for different OCCURs?

How urgent is this? The current plan is to
* release 0.5.5 with what we have, 
* merge changes prepared for 1.0.0 and work on other issues.

Have pressure from other projects, was planning to work on releasing 1.0.0 sometime next week.

**Comment by tr11** [comment]
No hurries at all.

The idea would be to specify for each field that depends on something else a mapping. With the example I had before:

```
   02 FIELD_TYPE                  PIC X.
   02 RECORD_TYPE_A OCCURS 0 TO 1 TIMES DEPENDING ON FIELD_TYPE.
       ....
   02 RECORD_TYPE_B OCCURS 0 TO 1 TIMES DEPENDING ON FIELD_TYPE.
       ....
```
A possible OCCURS mapping (json) would be
```
{
  "RECORD_TYPE_A": {
    "A": 1
  },
  "RECORD_TYPE_B": {
    "B": 1
  }
}
```

**Comment by tr11** [comment]
Actually, a better example would be
```
   02 FIELD_TYPE                  PIC X.
   02 RECORD_TYPE_A OCCURS 0 TO 2 TIMES DEPENDING ON FIELD_TYPE.
       ....
   02 RECORD_TYPE_B OCCURS 0 TO 2 TIMES DEPENDING ON FIELD_TYPE.
       ....
```
and the JSON mapping
```
{
  "RECORD_TYPE_A": {
    "A": 1,
    "X": 1,
    "Y": 2
  },
  "RECORD_TYPE_B": {
    "B": 1
    "X": 1,
    "Z": 2
  }
}
```

**Comment by yruslan** [comment]
Yes, this makes sense. Thanks!
