### ISSUE TITLE
Automatic segment redefines filtering

### ISSUE THREAD

**Issue by wrangel** [AbsaOSS/cobrix#153]
Hi Ruslan

After having managed to read in our custom variable record length files, we move on to efficiently loading the data into Spark.

Therefore, we intend to use automatic segment redefines filtering. 

Imagine the following set-up:

```
.option("segment_field", "SEGMENT")
.option("segment_id_level0", "0")
.option("segment_id_level1", "1")
.option("segment_id_level2", "2")
.option("redefine_segment_id_map:0", "HEADER_RECORD => "0")
.option("redefine_segment_id_map:1", "DATA_RECORD => "1")
.option("redefine_segment_id_map:2", "TRAILER_RECORD => "2")
```

Note that SEGMENT field values as well as the correspondent maps are tested and correct.

This example is following the guide in the docs closely. In fact, we would not need to specify the SEGMENT field values explicitly, they are already given.

From above setting we would expect the following outcome:

![Capture](https://user-images.githubusercontent.com/11014911/62630619-9a9b9600-b92f-11e9-90c2-78ed698738db.PNG)

However, this is the effective output:

![Capture2](https://user-images.githubusercontent.com/11014911/62630693-bbfc8200-b92f-11e9-8e92-c2aa242ebe78.PNG)

So, no setting irrelevant info to NULL.

If you'd need real data and metadata, you could use the material I sent you before. Together with our custom header parser implementation, it should be possible to reproduce the issue.

**Comment by yruslan** [comment]
Thanks for raising the issue. Will try to reproduce the issue without a custom header parser first. If it won't work, will ask you for your custom header parser implementation.

What is the size of the header in your custom record header parser? For RDWs it is 4 bytes. But if I remember correctly you have a much bigger header.

**Comment by yruslan** [comment]
Checked the code and the corresponding test. The way how segment id to redefine maps work should not be affected by a custom record header parser. So maybe this issue is related to something different. Could I ask you to post the exact dataframe reader command you use (with the paths renamed or removed)? I'd like to see how the combination of options affects automatic segment cleanup.

The above options look like not exact since it contains an additional double quote symbol in
```
.option("redefine_segment_id_map:0", "HEADER_RECORD => "0") 
```

**Comment by wrangel** [comment]
My bad with the options. Since I use a foldLeft to hover over the options (BTW: the option values for Cobrix mostly are String typed, sometimes also Boolean, such that I need to use 
`Seq[(String, Either[String, Boolean])]`, this is just a conversion typo.

In the meantime I was able to check automatic field filtering with standard fixed record length files. It does not work either. So I presume it has nothing to do with the additional custom parser options like `"rhp_additional_info"`

So, I would like to start with this simpler example. Find below my complete dataframe reader options: 

```
(spark read).format("cobol")
      .option("copybook", "path")
      .option("ebcdic_code_page", "cp037")
      .option("encoding", "EBCDIC")
      .option("is_record_sequence", "false")
      .option("schema_retention_policy", "collapse_root")
      .option("segment_field", "SEGMENT") 
      .option("segment_id_level0", "000")
      .option("segment_id_level1", "050")
      .option("segment_id_level2", "999")
      .option("redefine_segment_id_map:0", "HEADER_RECORD => 000")
      .option("redefine_segment_id_map:1", "DETAIL_RECORD => 050")
      .option("redefine_segment_id_map:2", "TRAILER_RECORD => 999")
      .load("fileName")
```

**Comment by yruslan** [comment]
Thanks, will try to run using your options.
Yeah, currently segment-redefine mapping does not work with fixed record length files. It is in the backlog for fixing. There is a possible workaround for that in #78.

**Comment by wrangel** [comment]
I confirm that the [workaround](https://github.com/AbsaOSS/cobrix/issues/78) works fine for fixed record length files. Nice! So let me clean up this loose end and come back to you with more insight in the variable record length file case later.

**Comment by yruslan** [comment]
Cool, will keep both #78 and this issue open until the mappings are implemented for fixed record length files.

**Comment by wrangel** [comment]
Redefines filtering is now working for both fixed and variable record length files, by using option `("generate_record_id", "true")`. I have not found any indication that options for custom header parser and redefines filtering are impeding one another, or that there is a bug at your end. Instead, I had to tweak the code on our side to make it work for variable record length. We are approaching an E2E ingesting solution for our special COBOL files here, thanks to your support.

**Comment by yruslan** [comment]
The segment-redefine mapping for fixed record length files is almost done. Will create the PR today most likely. This should improve performance for your case and `"generate_record_id", "true"` can be removed. Will let you know once a snapshot version is deployed to Maven.

**Comment by yruslan** [comment]
Deployed snapshot `0.5.5-SNAPSHOT`
