### ISSUE TITLE
Error handling comments in the new parser

### ISSUE THREAD

**Issue by yruslan** [AbsaOSS/cobrix#160]
A copybook:
```
      ******************************************************************
01234501  GRP_01.                                                       12345
000001   03 FIELD1     PIC X(1).                                        ABCDE
000002   03 FIELD2     PIC X(10).                                       34567
      ******************************************************************
*****************************************************************************
```
is a valid one. 
* The first 6 characters are considered comments and should be ignored.
* The character after the first 72 characters should be ignored.

However, the `1.0.0-SNAPSHOT` one thrown an error:
```
Syntax error in the copybook at line 2: Invalid input '01234501' at position 2:0
```

A unit test for this use case has been added to the `prepare_release_1_0_0` branch.

**Comment by tr11** [comment]
I was relying on the code path that stripped the first 6 and last characters after 72.  The parser assumes the input is already truncated.  
For that example, the parser should see 
```
******************************************************************
01  GRP_01.                                                       
   03 FIELD1     PIC X(1).                                        
   03 FIELD2     PIC X(10).                                       
******************************************************************
******************************************************************
```
which is parsed correctly.

**Comment by tr11** [comment]
I guess I removed the initial code I had that used the token splits!  I added a snippet of code to perform the correct line splicing.

**Comment by yruslan** [comment]
Thanks! I'm going to add an option to expect a copybook to be already truncated. Actually, more flexible, specify which characters to ignore at the start and at the end of lines.
