### ISSUE TITLE
Error handling field names with colons (':')

### ISSUE THREAD

**Issue by yruslan** [AbsaOSS/cobrix#161]
A copybook like this:
```
      01  :SOMETHING:-SOMETHING-DATE-NUM.
         03 :FIELD:1     PIC X(1).
         03 :FIELD:2     PIC X(10).
```
is considered a valid one by the old parser. The colon characters in field names are skipped.

However, the `1.0.0-SNAPSHOT` version throws the following error:
```
line 2:10 token recognition error at: ':'
line 2:20 token recognition error at: ':'
line 3:12 token recognition error at: ':'
line 3:18 token recognition error at: ':'
line 4:12 token recognition error at: ':'
line 4:18 token recognition error at: ':'
line 2:21 no viable alternative at input '01SOMETHING-'

Syntax error in the copybook at line 2: Invalid input '-' at position 2:21
za.co.absa.cobrix.cobol.parser.exceptions.SyntaxErrorException: Syntax error in the copybook at line 2: Invalid input '-' at position 2:21
```

A unit test for this use case has been added to the `prepare_release_1_0_0` branch.

**Comment by tr11** [comment]
Is that allowed? I thought colon characters were not allowed in field names.

**Comment by yruslan** [comment]
I think these copybooks that encounter these are some kind of copybook templates where something between colons is replaced by something else. But for some reason, we get those copybooks exactly like this. Ignoring colons works for all our purposes.
