### ISSUE TITLE
ParserVisitor fails parsing OccursTo

### ISSUE THREAD

**Issue by chandrasekaravr** [AbsaOSS/cobrix#172]
@yruslan Based on your suggestion from https://github.com/AbsaOSS/cobrix/issues/156#issuecomment-522518017, i tried with the **prepare_release_1_0_0**

This version is failing (with _NumberFormatException_) to parse the OccursTo section of my copybook,
`             04 CARR-CLM-VAR-GRP.
               06 NCH-EDIT-GRP OCCURS 0 TO 13 TIMES
                DEPENDING ON CARR-NCH-EDIT-CD-CNT.
                 08 NCH-EDIT-TRLR-IND-CD   PIC X.
                 08 NCH-EDIT-CD            PIC X(4).`

It is trying to parse the String _TO13_ instead of just _13_

**As an alternate:**
I initially tried with the current release tag _0.5.6_. And as pointed out in the above linked issue, the RDW is correctly decoded and all other sections are getting decoded, except for the OCCURS...DEPENDING ON... sections. 
It is correctly identifying the count value from _CARR-NCH-EDIT-CD-CNT_ and adds that many number repeating groups in the output. However, all the fields in the groups are empty.

**Comment by tr11** [comment]
Could you paste/send the whole copybook? That snippet is parsed correctly on my machine.

**Comment by chandrasekaravr** [comment]
@yruslan I have pasted the whole copybook here. 
For the branch **prepare_release_1_0_0**, i had to remove the _OF CARR-CLM-REC._ from the _DEPENDING ON_ 

`     *
      *       MEMBER  CARR_CLM_K_REC
           02 CARR-CLM-REC.
      *    ***********************************************************
      *    *  UTLCARRK,  NCH INTERNAL FORMAT (VERSION K)
      *    *  CARRIER CLAIM RECORD (OTHER THAN DMERC)
      *    ***********************************************************
             04 CARR-CLM-FIX-GRP.
               06 CLM-REC-IDENT-GRP.
                 08 REC-LNGTH-CNT          PIC S9(5) COMP-3.
                 08 NCH-NEAR-LINE-REC-VRSN-CD
                                           PIC X.
                 08 NCH-NEAR-LINE-RIC-CD
                                           PIC X.
                 08 NCH-MQA-RIC-CD         PIC X.
                 08 NCH-CLM-TYPE-CD        PIC XX.
               06 CARR-DMERC-CLM-LINK-GRP.
                 08 CLM-LCTR-NUM-GRP.
                   10 BENE-CLM-ACNT-NUM    PIC X(9).
                   10 NCH-CTGRY-EQTBL-BIC-CD
                                           PIC XX.
                 08 BENE-IDENT-CD          PIC XX.
                 08 NCH-STATE-SGMT-CD      PIC X.
                 08 BENE-RSDNC-SSA-STD-STATE-CD
                                           PIC XX.
                 08 CLM-FROM-DT            PIC 9(8).
                 08 CLM-THRU-DT            PIC 9(8).
                 08 NCH-WKLY-PROC-DT       PIC 9(8).
                 08 CWF-CLM-ACRTN-DT       PIC 9(8).
                 08 CWF-CLM-ACRTN-NUM      PIC S999 COMP-3.
                 08 CARR-CLM-CNTL-NUM      PIC X(15).
                 08 H-FILLER-1             PIC X(38).
                 08 NCH-DAILY-PROC-DT      PIC 9(8).
                 08 NCH-SGMT-LINK-NUM      PIC S9(9) COMP-3.
                 08 CLM-TOT-SGMT-CNT       PIC 99.
                 08 CLM-SGMT-NUM           PIC 99.
                 08 CLM-TOT-LINE-CNT       PIC 999.
                 08 CLM-SGMT-LINE-CNT      PIC 99.
               06 CARR-DMERC-CLM-CMN-1-GRP.
                 08 H-FILLER-2             PIC X(5).
                 08 CARR-CLM-ENTRY-CD      PIC X.
                 08 H-FILLER-3             PIC X.
                 08 CLM-DISP-CD            PIC XX.
                 08 NCH-EDIT-DISP-CD       PIC XX.
                 08 NCH-CLM-BIC-MDFY-CD    PIC X.
                 08 BENE-RSDNC-SSA-STD-CNTY-CD
                                           PIC XXX.
                 08 CARR-CLM-RCPT-DT       PIC 9(8).
                 08 CARR-CLM-SCHLD-PMT-DT
                                           PIC 9(8).
                 08 CWF-FRWRD-DT           PIC 9(8).
                 08 CARR-NUM               PIC X(5).
                 08 H-FILLER-4             PIC X(8).
                 08 CWF-TRNSMSN-BATCH-NUM  PIC X(4).
                 08 BENE-MLG-CNTCT-ZIP-CD  PIC X(9).
                 08 BENE-SEX-IDENT-CD      PIC X.
                 08 BENE-RACE-CD           PIC X.
                 08 BENE-BIRTH-DT          PIC 9(8).
                 08 CWF-BENE-MDCR-STUS-CD
                                           PIC XX.
                 08 CLM-PTNT-6-PSTN-SRNM-NAME
                                           PIC X(6).
                 08 CLM-PTNT-1ST-INITL-GVN-NAME
                                           PIC X.
                 08 CLM-PTNT-1ST-INITL-MDL-NAME
                                           PIC X.
                 08 BENE-CWF-LOC-CD        PIC X.
                 08 CLM-PRNCPAL-DGNS-GRP.
                     10 CLM-PRNCPAL-DGNS-VRSN-CD
                                           PIC X.
                     10 CLM-PRNCPAL-DGNS-CD
                                            PIC X(7).
                 08 H-FILLER-5              PIC X.
                 08 CARR-CLM-PMT-DNL-CD     PIC XX.
                 08 CLM-EXCPTD-NEXCPTD-TRTMT-CD
                                            PIC X.
                 08 CLM-PMT-AMT             PIC S9(9)V99 COMP-3.
                 08 CARR-CLM-PRMRY-PYR-PD-AMT
                                            PIC S9(9)V99 COMP-3.
                 08 H-FILLER-6             PIC X.
                 08 CARR-CLM-RFRG-UPIN-NUM PIC X(6).
                 08 CARR-CLM-RFRG-PHYSN-NPI-NUM
                                           PIC X(10).
                 08 CARR-CLM-PRVDR-ASGNMT-IND-SW
                                           PIC X.
                 08 NCH-CLM-PRVDR-PMT-AMT  PIC S9(9)V99 COMP-3.
                 08 NCH-CLM-BENE-PMT-AMT   PIC S9(9)V99 COMP-3.
                 08 CARR-CLM-BENE-PD-AMT   PIC S9(9)V99 COMP-3.
                 08 NCH-CARR-SBMT-CHRG-AMT PIC S9(9)V99 COMP-3.
                 08 NCH-CARR-ALOW-CHRG-AMT PIC S9(9)V99 COMP-3.
                 08 CARR-CLM-CASH-DDCTBL-APPLY-AMT
                                           PIC S9(9)V99 COMP-3.
                 08 CARR-CLM-HCPCS-YR-CD   PIC 9.
                 08 CARR-CLM-MCO-OVRRD-IND-CD
                                           PIC X.
                 08 CARR-CLM-HOSPC-OVRRD-IND-CD
                                           PIC X.
                 08 CLM-BUSNS-SGMT-ID-CD   PIC X(4).
                 08 CLM-CLNCL-TRIL-NUM     PIC X(8).
                 08 CLM-RAC-ADJSTMT-IND-CD PIC X(1).
                 08 CLM-PWK-CD             PIC X(2).                    01010001
                 08 CLM-CARE-IMPRVMT-MODEL-1-CD
                                           PIC X(2).
                 08 CLM-CARE-IMPRVMT-MODEL-2-CD
                                           PIC X(2).
                 08 CLM-CARE-IMPRVMT-MODEL-3-CD
                                           PIC X(2).
                 08 CLM-CARE-IMPRVMT-MODEL-4-CD
                                           PIC X(2).
                 08 CLM-FPS-MODEL-NUM      PIC X(2).
                 08 CLM-FPS-RSN-CD         PIC X(3).
                 08 CLM-FPS-RMRK-CD        PIC X(5).
                 08 CLM-FPS-MSN-1-CD       PIC X(5).
                 08 CLM-FPS-MSN-2-CD       PIC X(5).
                 08 CLM-MASS-ADJSTMT-IND-CD
                                           PIC X.
                 08 CLM-PAPER-PRVDR-CD     PIC X(2).
                 08 CLM-RSDL-PMT-IND-CD    PIC X.                       01020001
                 08 CLM-ACO-ID-NUM         PIC X(10).                   01020001
                 08 MBI-ID                 PIC X(11).                   01020001
                 08 CLM-BENE-ID-TYPE-CD    PIC X.                       01020001
                 08 CLM-PRVDR-VLDTN-CD     PIC X(2).                    01020001
                 08 H-FILLER-7             PIC X(673).                  01020001
               06 CARR-SPECFC-GRP.
                 08 CARR-CLM-RFRG-PIN-NUM  PIC X(14).
                 08 CPO-PRVDR-NUM          PIC X(6).
                 08 CPO-ORG-NPI-NUM        PIC X(10).
                 08 CLM-BLOOD-PT-FRNSH-QTY PIC S999 COMP-3.
                 08 CLM-BLOOD-DDCTBL-PT-QTY
                                           PIC S999 COMP-3.
                 08 CARR-CLM-BLG-NPI-NUM   PIC X(10).
                 08 CARR-CLM-SOS-NPI-NUM   PIC X(10).
                 08 H-FILLER-8             PIC X(480).
               06 CARR-NCH-EDIT-CD-CNT     PIC 99.
               06 CARR-NCH-PATCH-CD-I-CNT  PIC 99.
               06 CARR-MCO-PRD-CNT         PIC 9.
               06 CARR-CLM-DEMO-ID-CNT     PIC 9.
               06 CARR-CLM-DGNS-CD-J-CNT   PIC 99.
               06 CARR-CLM-LINE-CNT        PIC 99.
               06 H-FILLER-9               PIC X(4).
             04 CARR-CLM-VAR-GRP.
               06 NCH-EDIT-GRP          OCCURS 0 TO 13 TIMES
                DEPENDING ON CARR-NCH-EDIT-CD-CNT.
                 08 NCH-EDIT-TRLR-IND-CD   PIC X.
                 08 NCH-EDIT-CD            PIC X(4).
               06 NCH-PATCH-GRP         OCCURS 0 TO 30 TIMES
                DEPENDING ON CARR-NCH-PATCH-CD-I-CNT
                          OF CARR-CLM-REC.
                 08 NCH-PATCH-TRLR-IND-CD
                                           PIC X.
                 08 NCH-PATCH-CD           PIC XX.
                 08 NCH-PATCH-APPLY-DT     PIC 9(8).
               06 MCO-PRD-GRP           OCCURS 0 TO 2 TIMES
                                        DEPENDING ON CARR-MCO-PRD-CNT
                          OF CARR-CLM-REC.
                 08 NCH-MCO-TRLR-IND-CD    PIC X.
                 08 MCO-CNTRCT-NUM         PIC X(5).
                 08 MCO-OPTN-CD            PIC X.
                 08 MCO-PRD-EFCTV-DT       PIC 9(8).
                 08 MCO-PRD-TRMNTN-DT      PIC 9(8).
                 08 MCO-HLTH-PLANID-NUM    PIC X(14).
               06 CLM-DEMO-ID-GRP       OCCURS 0 TO 5 TIMES
                DEPENDING ON CARR-CLM-DEMO-ID-CNT
                          OF CARR-CLM-REC.
                 08 NCH-DEMO-TRLR-IND-CD
                                           PIC X.
                 08 CLM-DEMO-ID-NUM        PIC XX.
                 08 CLM-DEMO-INFO-TXT      PIC X(15).
               06 CARR-CLM-DGNS-GRP     OCCURS 0 TO 12 TIMES
                DEPENDING ON CARR-CLM-DGNS-CD-J-CNT
                          OF CARR-CLM-REC.
                 08 NCH-DGNS-TRLR-IND-CD
                                           PIC X.
                 08 CLM-DGNS-VRSN-CD       PIC X.
                 08 CLM-DGNS-CD            PIC X(7).
               06 CARR-LINE-GRP         OCCURS 1 TO 13 TIMES
                                        DEPENDING ON CARR-CLM-LINE-CNT
                          OF CARR-CLM-REC.
                 08 NCH-LINE-TRLR-IND-CD   PIC X.
                 08 CARR-LINE-PRFRMG-PIN-NUM
                                           PIC X(10).
                 08 CARR-LINE-PRFRMG-UPIN-NUM
                                           PIC X(6).
                 08 CARR-LINE-PRFRMG-NPI-NUM
                                           PIC X(10).
                 08 CARR-LINE-PRFRMG-GRP-NPI-NUM
                                           PIC X(10).
                 08 CARR-LINE-PRVDR-TYPE-CD
                                           PIC X.
                 08 LINE-PRVDR-TAX-NUM     PIC X(10).
                 08 LINE-NCH-PRVDR-STATE-CD
                                           PIC XX.
                 08 CARR-LINE-PRFRMG-PRVDR-ZIP-CD
                                           PIC X(9).
                 08 LINE-HCFA-PRVDR-SPCLTY-CD
                                           PIC XX.
                 08 CARR-LINE-PRVDR-SPCLTY-CD
                                           PIC XX.
                 08 LINE-PRVDR-PRTCPTG-IND-CD
                                           PIC X.
                 08 CARR-LINE-RDCD-PHYSN-ASTNT-CD
                                           PIC X.
                 08 LINE-SRVC-CNT          PIC S9(7)V999 COMP-3.
                 08 LINE-HCFA-TYPE-SRVC-CD PIC X.
                 08 CARR-LINE-TYPE-SRVC-CD PIC XX.
                 08 LINE-PLC-SRVC-CD       PIC XX.
                 08 CARR-LINE-PRCNG-LCLTY-CD
                                           PIC XX.
                 08 LINE-1ST-EXPNS-DT      PIC 9(8).
                 08 LINE-LAST-EXPNS-DT     PIC 9(8).
                 08 LINE-HCPCS-CD          PIC X(5).
                 08 LINE-HCPCS-INITL-MDFR-CD
                                           PIC XX.
                 08 LINE-HCPCS-2ND-MDFR-CD
                                           PIC XX.
                 08 LINE-HCPCS-3RD-MDFR-CD                              00019300
                                           PIC XX.                      00019400
                 08 LINE-HCPCS-4TH-MDFR-CD                              00019500
                                           PIC XX.                      00019600
                 08 LINE-NCH-BETOS-CD      PIC XXX.
                 08 LINE-IDE-NUM           PIC X(7).
                 08 LINE-NATL-DRUG-CD      PIC X(11).
                 08 LINE-NCH-PMT-AMT       PIC S9(9)V99 COMP-3.
                 08 LINE-BENE-PMT-AMT      PIC S9(9)V99 COMP-3.
                 08 LINE-PRVDR-PMT-AMT     PIC S9(9)V99 COMP-3.
                 08 LINE-BENE-PTB-DDCTBL-AMT
                                           PIC S9(9)V99 COMP-3.
                 08 LINE-BENE-PRMRY-PYR-CD
                                           PIC X.
                 08 LINE-BENE-PRMRY-PYR-PD-AMT
                                           PIC S9(9)V99 COMP-3.
                 08 LINE-COINSRNC-AMT      PIC S9(9)V99 COMP-3.
                 08 CARR-LINE-PSYCH-OT-PT-LMT-AMT
                                           PIC S9(9)V99 COMP-3.
                 08 LINE-INTRST-AMT        PIC S9(9)V99 COMP-3.
                 08 LINE-PRMRY-PYR-ALOW-CHRG-AMT
                                           PIC S9(9)V99 COMP-3.
                 08 LINE-10PCT-PNLTY-RDCTN-AMT
                                           PIC S9(9)V99 COMP-3.
                 08 CARR-LINE-BLOOD-DDCTBL-QTY
                                           PIC S999 COMP-3.
                 08 LINE-SBMT-CHRG-AMT     PIC S9(9)V99 COMP-3.
                 08 LINE-ALOW-CHRG-AMT     PIC S9(9)V99 COMP-3.
                 08 CARR-LINE-CLNCL-LAB-NUM
                                           PIC X(10).
                 08 CARR-LINE-CLNCL-LAB-CHRG-AMT
                                           PIC S9(9)V99 COMP-3.
                 08 LINE-PRCSG-IND-CD      PIC XX.
                 08 LINE-PMT-80-100-CD     PIC X.
                 08 LINE-SRVC-DDCTBL-IND-SW
                                           PIC X.
                 08 LINE-PMT-IND-CD        PIC X.
                 08 CARR-LINE-MTUS-CNT     PIC S9(7)V999 COMP-3.
                 08 CARR-LINE-MTUS-IND-CD
                                           PIC X.
                 08 LINE-DGNS-GRP.
                    10 LINE-DGNS-VRSN-CD
                                           PIC X.
                    10 LINE-DGNS-CD        PIC X(7).
                 08 CARR-LINE-ANSTHSA-UNIT-CNT
                                           PIC S9(7)V999 COMP-3.
                 08 CARR-LINE-CLIA-ALERT-IND-CD
                                           PIC X.
                 08 LINE-ADDTNL-CLM-DCMTN-IND-CD
                                           PIC X.
                 08 CARR-LINE-DME-CVRG-PRD-STRT-DT
                                           PIC 9(8).
                 08 LINE-DME-PURC-PRICE-AMT
                                           PIC S9(9)V99 COMP-3.
                 08 CARR-LINE-DME-NCSTY-MO-CNT
                                           PIC S999 COMP-3.
                 08 LINE-CNSLDTD-BLG-CD    PIC X.
                 08 LINE-DUP-CLM-CHK-IND-CD
                                           PIC X.
                 08 CARR-LINE-PNT-PCKP-ZIP-CD
                                           PIC X(9).
                 08 CARR-LINE-DROP-OFF-ZIP-CD
                                           PIC X(9).
                 08 CARR-LINE-HPSA-SCRCTY-IND-CD
                                           PIC X.
                 08 CARR-LINE-RX-NUM       PIC X(30).
                 08 LINE-HCT-HGB-TYPE-CD
                                           PIC X(2).
                 08 LINE-HCT-HGB-RSLT-NUM
                                           PIC X(03).
                 08 LINE-HCT-HGB-RSLT-NUM-R  REDEFINES
                    LINE-HCT-HGB-RSLT-NUM
                                           PIC 99V9.

                 08 LINE-WC-IND-CD         PIC X(1).
                 08 LINE-PWK-CD            PIC X(2).                    02690001
                 08 LINE-UNIQ-TRKNG-NUM
                                           PIC X(14).
                 08 LINE-POS-PHYSN-ORG-NAME
                                           PIC X(60).
                 08 LINE-POS-PHYSN-1ST-NAME
                                           PIC X(35).
                 08 LINE-POS-PHYSN-MDL-NAME
                                           PIC X(25).
                 08 LINE-POS-PHYSN-ADR-1-NAME
                                           PIC X(55).
                 08 LINE-POS-PHYSN-ADR-2-NAME
                                           PIC X(55).
                 08 LINE-POS-PHYSN-CITY-NAME
                                           PIC X(30).
                 08 LINE-POS-PHYSN-STATE-CD
                                           PIC X(2).
                 08 LINE-POS-PHYSN-ZIP-CD  PIC X(15).
                 08 LINE-OTHR-APLD-IND-1-CD
                                           PIC X.
                 08 LINE-OTHR-APLD-IND-2-CD
                                           PIC X.
                 08 LINE-OTHR-APLD-IND-3-CD
                                           PIC X.
                 08 LINE-OTHR-APLD-IND-4-CD
                                           PIC X.
                 08 LINE-OTHR-APLD-IND-5-CD
                                           PIC X.
                 08 LINE-OTHR-APLD-IND-6-CD
                                           PIC X.
                 08 LINE-OTHR-APLD-IND-7-CD
                                           PIC X.
                 08 LINE-OTHR-APLD-1-AMT   PIC S9(9)V99 COMP-3.
                 08 LINE-OTHR-APLD-2-AMT   PIC S9(9)V99 COMP-3.
                 08 LINE-OTHR-APLD-3-AMT   PIC S9(9)V99 COMP-3.
                 08 LINE-OTHR-APLD-4-AMT   PIC S9(9)V99 COMP-3.
                 08 LINE-OTHR-APLD-5-AMT   PIC S9(9)V99 COMP-3.
                 08 LINE-OTHR-APLD-6-AMT   PIC S9(9)V99 COMP-3.
                 08 LINE-OTHR-APLD-7-AMT   PIC S9(9)V99 COMP-3.
                 08 LINE-THRPY-CAP-IND-1-CD
                                           PIC X.
                 08 LINE-THRPY-CAP-IND-2-CD
                                           PIC X.
                 08 LINE-THRPY-CAP-IND-3-CD
                                           PIC X.
                 08 LINE-THRPY-CAP-IND-4-CD
                                           PIC X.
                 08 LINE-THRPY-CAP-IND-5-CD
                                           PIC X.
                 08 LINE-FPS-MODEL-NUM     PIC X(2).
                 08 LINE-FPS-RSN-CD        PIC X(3).
                 08 LINE-FPS-RMRK-CD       PIC X(5).
                 08 LINE-FPS-MSN-1-CD      PIC X(5).
                 08 LINE-FPS-MSN-2-CD      PIC X(5).
                 08 LINE-RNDRNG-BLG-NPI-ASCTN-CD
                                           PIC X.
                 08 LINE-PRIOR-AUTHRZTN-IND-CD
                                           PIC X(4).
                 08 LINE-NG-ACO-IND-1-CD   PIC X.
                 08 LINE-NG-ACO-IND-2-CD   PIC X.
                 08 LINE-NG-ACO-IND-3-CD   PIC X.
                 08 LINE-NG-ACO-IND-4-CD   PIC X.
                 08 LINE-NG-ACO-IND-5-CD   PIC X.
                 08 LINE-RP-IND-CD         PIC X.
                 08 LINE-RSDL-PMT-IND-CD   PIC X.
                 08 CARR-LINE-MDPP-NPI-NUM PIC X(10).
                 08 CARR-LINE-PRVDR-VLDTN-CD
                                           PIC X(2).
                 08 H-FILLER-10            PIC X(976).                  02700001
               06 END-REC-CD               PIC XXX.
`

**Comment by tr11** [comment]
Can you use pastebin or a gist?  The formatting (including line breaks) is relevant for this issue.

**Comment by chandrasekaravr** [comment]
@tr11 here is the gist for this copybook, <script src="https://gist.github.com/chandrasekaravr/2cce4899b846e8bf82e02a5a077a54b0.js"></script>

**Comment by tr11** [comment]
Regarding the `OF CARR-CLM-REC` part, I've never seen the `OF` clause.  Do you have some documentation to what it's supposed to do?

**Comment by chandrasekaravr** [comment]
@tr11 here is the link for the gist, https://gist.github.com/chandrasekaravr/2cce4899b846e8bf82e02a5a077a54b0

The _OF_ part refers to the group above that contains the count field. For now, it can be ignored. I have updated the gist with a fixed copybook.

**Comment by tr11** [comment]
I see, right now we just look for all the matching names so we'll need to add logic to the parser to handle the `OF` clause. That said, if there are no name clashes, that clause becomes redundant so probably not a priority for now.

Take a look at the PR #173 -- the `TO13` was a bug in the code. That PR solves this issue.

**Comment by chandrasekaravr** [comment]
@tr11 Great. Thanks for taking care of the bug. 
The _OF_ clause is not a blocker, as you said. Since there is no name clash, the parser is correctly identifying the group and creating an array of correct size. However, the group fields are empty. Any suggestions on that?

**Comment by yruslan** [comment]
Thanks for the analysis. It is very helpful for our understanding of the issue.

Yes, currently if an array is present in a data file it is expected to always occupy the same space as it would take to store the maximum number of elements of such an array. Even if a particular instance of an array has 0 elements, the record is expected to have bytes for that array filled.

Up until now, we haven't encountered any copybooks that contain variable size arrays that shrink depending on the number of array elements. We can add support for such arrays in one of the future releases.

Just a couple of questions to clarify.
1. Let's say a copybook has an array of 0-3 with a 'depending on' clause. If the value of the dependent field is 0, then no bytes of that array is present in the data file, right?
2. If (1) is true, what happens if the value of the dependent field is 1? Will the record contain only bytes for 1 element, or it will contain bytes for 3 (maximum) elements?
Please, let me know if you need me to elaborate on the questions.

If you could provide a simplified example of a copybook and a data file so we are sure our implementation is aligned to your expectations, it would make it much easier for us.

**Comment by yruslan** [comment]
Great. So the above is true for every array that has 'depending on' clause in the copybook, right?

We might implement it as an option for `spark-cobol`, e.g. `.option(...)`.

**Comment by yruslan** [comment]
Interesting. It is always false (the current behavior) for our copybooks.

**Comment by chandrasekaravr** [comment]
@tr11 @yruslan 
Thanks for looking into this. I will follow this enhancement.
I have updated this gist with the sample data file, https://gist.github.com/chandrasekaravr/2cce4899b846e8bf82e02a5a077a54b0

It has the copybook and a sample data file that is of variable length and has RDW.

**Comment by yruslan** [comment]
👍  Thanks for the data!

**Comment by yruslan** [comment]
Please, try this snapshot and let me know if it worked for you:
```xml
<dependency>
      <groupId>za.co.absa.cobrix</groupId>
      <artifactId>spark-cobol</artifactId>
      <version>1.0.1-SNAPSHOT</version>
</dependency>
```
You also need to use this option:
```
.option("variable_size_occurs", "true")
```

**Comment by chandrasekaravr** [comment]
@yruslan Thank you. Will try this out.

**Comment by chandrasekaravr** [comment]
@yruslan Thanks for the quick enhancement. I tried the 1.0.1.SNAPSHOT. And it parsed out the variable length data file with the varying array sizes beautifully.
I have a question with respect to multisegment data file processing. I experienced the same with your `test5` test data also. This is what i observed, 
1. The data file is multisegmented, ie, multiple record types in the same file ( **C** for _Static-Details_ and **P** for _Contacts_) [_ref: ../data/test5_data_]
2. The copy book has the different record types varying groups defined as _REDEFINES_ [_ref: ../data/test5_copybook.cob_]
3. I expected either _Static-Details_  OR  _Contacts_ to be present, depending on the segment ID, but the content is getting extracted as both groups (ofcourse, one being incorrect). The expected test results file also has such output for each record. [_ref: ../data/test5_expected/test5.txt_]

Is this the expected result?

**Comment by yruslan** [comment]
Happy the variable size arrays worked for you. Going to release 1.0.1 today with these changes.

Yes, this is the expected behavior since Copybooks do not contain information on how to distinguish between segments. 

You can use `redefine-segment-id-map` set of options to specify a mapping between segment redefines and segment ids. If you do so Cobrix will parse proper segments automatically. The usage is described in README, and also you can take a look at the same Test5 for an example. Look for:
```
      .option("redefine_segment_id_map:0", "STATIC-DETAILS => C,D")
      .option("redefine-segment-id-map:1", "CONTACTS => P")
```

**Comment by chandrasekaravr** [comment]
@yruslan Thanks for the tip. It worked perfectly. I was using the _segment_filter_ and _segment_field_` initially.
