### ISSUE TITLE
Refactor AST internals

### ISSUE THREAD

**Issue by yruslan** [AbsaOSS/cobrix#191]
## Background
Initially, AST was defined as an `Array[Group]`. It complicated AST traversal since the root node had to be processed separately from each instance of `Group`.
Since then, the parser was refactored, so that AST is now a `Group`. But in many places of the code legacy `Array[Group]` is used.

E.g.
```scala
  type MutableCopybook = mutable.ArrayBuffer[Statement]
  type CopybookAST = Group
```
This leads to expressions like this:
```scala
val newSchema = processRootLevelFields(originalSchema.head.asInstanceOf[Group].children)
```

# Task
Remove `MutableCopybook` type and always use `CopybookAST`. This should transform expressions similar to above into:
```scala
val newSchema = processGroup(originalSchema)
```

**Comment by tr11** [comment]
I can probably help with this.
