### ISSUE TITLE
Automatic reconstruction of hierarchical record structure spark-cobol 1.1.0v not available

### ISSUE THREAD

**Issue by krpraveen01** [AbsaOSS/cobrix#205]
Hi,

Can you tell me which version of scala-cobol jar supports Automatic reconstruction of hierarchical record structure. The article says 1.1.0 supports but ididn't find this jar.

Thanks,
KR

**Comment by yruslan** [comment]
Hi, thanks for the interest in the feature. Currently, it is available in the snapshot version `1.1.0-SNAPSHOT`. `1.1.0` will be released next week after additional testing.
Looking forward to any feedback on the feature.

**Comment by krpraveen01** [comment]
HI,
Thanks for the quick response. i am getting the below error while adding the snapshot version dependency.
Could not resolve dependencies for project com.example:spark-codec-app:jar:0.0.1-SNAPSHOT: Could not find artifact za.co.absa.cobrix:spark-cobol:jar:1.1.0-SNAPSHOT. 
Thanks You,
KR

**Comment by yruslan** [comment]
Snapshot repositories need to be explicitly enabled in Maven configuration in order for this to work.
See https://stackoverflow.com/questions/7715321/how-to-download-snapshot-version-from-maven-snapshot-repository

**Comment by krpraveen01** [comment]
Hi,
When I tried with Snapshot version jar, i am able to build the project but not able to execute the MultiSegement.java example.  I am getting the below error :
Exception in thread "main" java.lang.NoSuchMethodError: za.co.absa.cobrix.cobol.parser.CopybookParser$.parseTree(Lza/co/absa/cobrix/cobol/parser/encoding/Encoding;Ljava/lang/String;ZLscala/collection/Seq;Lscala/collection/immutable/Map;Lscala/Enumeration$Value;Lza/co/absa/cobrix/cobol/parser/policies/CommentPolicy;Lza/co/absa/cobrix/cobol/parser/encoding/codepage/CodePage;Lscala/Enumeration$Value;Lscala/collection/Seq;)Lza/co/absa/cobrix/cobol/parser/Copybook;
Can you tell me if i need to set anything else.
Thank You,
KR

**Comment by yruslan** [comment]
You can use `1.1.0` version, it was released just now. 😄

**Comment by krpraveen01** [comment]
Hi,
I tried the latest 1.1.0 version but getting the below error
Exception in thread "main" java.lang.NoSuchMethodError: za.co.absa.cobrix.cobol.parser.CopybookParser$.parseTree(Lza/co/absa/cobrix/cobol/parser/encoding/Encoding;Ljava/lang/String;ZLscala/collection/Seq;Lscala/collection/immutable/Map;Lscala/Enumeration$Value;Lza/co/absa/cobrix/cobol/parser/policies/CommentPolicy;Lza/co/absa/cobrix/cobol/parser/encoding/codepage/CodePage;Lscala/Enumeration$Value;Lscala/collection/Seq;)Lza/co/absa/cobrix/cobol/parser/Copybook;
	at za.co.absa.cobrix.spark.cobol.reader.varlen.VarLenNestedReader.loadCopyBook(VarLenNestedReader.scala:133)
 Can you help us fixing this issue.
Thanks,
Raj

**Comment by yruslan** [comment]
Sure. Please send the code you are trying to execute and the command line used.

**Comment by krpraveen01** [comment]
Hi, 
I got the latest zip project and was able to package it with warnings but when i try to do 'mvn package -DskipTests' as per README doc on examples/spark-cobol-app , I am getting the below errors:
[ERROR] error: error while loading package, invalid LOC header (bad signature)
[ERROR] error: error while loading functions, invalid LOC header (bad signature)
[ERROR] error: error while loading DataFrameReader, invalid LOC header (bad signature)
[ERROR] error: error while loading SQLImplicits, invalid LOC header (bad signature)
[ERROR] workspce\cobrix\examples\spark-cobol-app\src\main\scala\com\example\spark\cobol\app\SparkCobolApp.scala:101: error: value format is not a member of org.apache.spark.sql.DataFrameReader
[ERROR] possible cause: maybe a semicolon is missing before `value format'?
[ERROR]       .format("cobol")                                     // Alternatively can use "za.co.absa.cobrix.spark.cobol.source"
[ERROR]        ^
[ERROR] workspce\cobrix\examples\spark-cobol-app\src\main\scala\com\example\spark\cobol\app\SparkCobolHierarchical.scala:97: error: value format is not a member of org.apache.spark.sql.DataFrameReader
[ERROR] possible cause: maybe a semicolon is missing before `value format'?
[ERROR]       .format("cobol")                             // Alternatively can use "za.co.absa.cobrix.spark.cobol.source"
[ERROR]        ^
[ERROR] workspce\cobrix\examples\spark-cobol-app\src\main\scala\com\example\spark\cobol\app\SparkCodecApp.scala:42: error: value format is not a member of org.apache.spark.sql.DataFrameReader
[ERROR] possible cause: maybe a semicolon is missing before `value format'?
[ERROR]       .format("cobol")
[ERROR]        ^
[ERROR] workspce\cobrix\examples\spark-cobol-app\src\main\scala\com\example\spark\cobol\app\SparkTypesApp.scala:56: error: value format is not a member of org.apache.spark.sql.DataFrameReader
[ERROR] possible cause: maybe a semicolon is missing before `value format'?
[ERROR]       .format("cobol")                                        // Alternatively can use "za.co.absa.cobrix.spark.cobol.source"
[ERROR]        ^
[ERROR] 8 errors found
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE

**Comment by yruslan** [comment]
Try just
```
mvn package
```
Tests can be skipped by running
```
mvn package -DskipTests=true
```
(will fix the README later)

Works for me on both Windows and MacOS.
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.331 s
[INFO] Finished at: 2019-11-12T18:59:50+01:00
[INFO] Final Memory: 38M/916M
[INFO] ------------------------------------------------------------------------
```
Warnings are fine since we are building a fat jar using shade plugin and dependencies have overlapped classes.

**Comment by krpraveen01** [comment]
Got same issue with both mvn cmds:

workspce\cobrix\examples\spark-cobol-app>mvn package
[INFO] Scanning for projects...
[INFO]
[INFO] --------------------< com.example:spark-cobol-app >---------------------
[INFO] Building spark-cobol-app 0.0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ spark-cobol-app ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory workspce\cobrix\examples\spark-cobol-app\src\main\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ spark-cobol-app ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- scala-maven-plugin:3.3.1:compile (default) @ spark-cobol-app ---
[INFO] workspce\cobrix\examples\spark-cobol-app\src\main\scala:-1: info: compiling
[INFO] Compiling 5 source files to workspce\cobrix\examples\spark-cobol-app\target\classes at 1573582416912
[ERROR] error: error while loading package, invalid LOC header (bad signature)
[ERROR] error: error while loading functions, invalid LOC header (bad signature)
[ERROR] error: error while loading DataFrameReader, invalid LOC header (bad signature)
[ERROR] error: error while loading SQLImplicits, invalid LOC header (bad signature)
[ERROR] workspce\cobrix\examples\spark-cobol-app\src\main\scala\com\example\spark\cobol\app\SparkCobolApp.scala:101: error: value format is not a member of org.apache.spark.sql.DataFrameReader
[ERROR] possible cause: maybe a semicolon is missing before `value format'?
[ERROR]       .format("cobol")                                     // Alternatively can use "za.co.absa.cobrix.spark.cobol.source"
[ERROR]        ^
[ERROR] workspce\cobrix\examples\spark-cobol-app\src\main\scala\com\example\spark\cobol\app\SparkCobolHierarchical.scala:97: error: value format is not a member of org.apache.spark.sql.DataFrameReader
[ERROR] possible cause: maybe a semicolon is missing before `value format'?
[ERROR]       .format("cobol")                             // Alternatively can use "za.co.absa.cobrix.spark.cobol.source"
[ERROR]        ^
[ERROR] workspce\cobrix\examples\spark-cobol-app\src\main\scala\com\example\spark\cobol\app\SparkCodecApp.scala:42: error: value format is not a member of org.apache.spark.sql.DataFrameReader
[ERROR] possible cause: maybe a semicolon is missing before `value format'?
[ERROR]       .format("cobol")
[ERROR]        ^
[ERROR] workspce\cobrix\examples\spark-cobol-app\src\main\scala\com\example\spark\cobol\app\SparkTypesApp.scala:56: error: value format is not a member of org.apache.spark.sql.DataFrameReader
[ERROR] possible cause: maybe a semicolon is missing before `value format'?
[ERROR]       .format("cobol")                                        // Alternatively can use "za.co.absa.cobrix.spark.cobol.source"
[ERROR]        ^
[ERROR] 8 errors found
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  11.804 s
[INFO] Finished at: 2019-11-12T13:13:40-05:00

**Comment by yruslan** [comment]
Not sure, might be a corrupted cached JAR in one of the cached Maven dependencies.
Try renaming/deleting your `.m2` folder and rerun the command.

**Comment by krpraveen01** [comment]
Hi,
I cleaned up the .m2 and did the new package , i am able to run all the sample test cases successfully now.
Thank You...
