### ISSUE TITLE
usage question

### ISSUE THREAD

**Issue by plreddy** [AbsaOSS/cobrix#231]
Hi,
this is not a issue just a usage question. i am new to Spark and cobrix. i am checking the examples to see how can i use it.

for one the example as below , the program is automatically creating the schema based on copy book , is it possible to define my own schema, like high lighted below

[Builder sparkBuilder = SparkSession.builder().appName("CobolJava1");
		SparkSession session = sparkBuilder.master("local[*]").getOrCreate();

		Dataset<Row> dataset = session.read().format("cobol")
				.option("copybook", "/Users/user/eclipsews/spark1/src/main/resources/raw_file.cob")
				.option("schema_retention_policy", "collapse_root").**schema(MainframeSchema.getMainFrameSchema())**
				.load("src/main/resources/file1.bin");

		dataset.printSchema();

		Encoder<MainframeRecord> encoder = Encoders.bean(MainframeRecord.class);
		Dataset<MainframeRecord> dataset2 = dataset.as(encoder);

		dataset2.show();]

schema definiation looks something like this.

```

StructField[] accountDetailFields = new StructField[] {
				new StructField("accountNumber", DataTypes.StringType, false, Metadata.empty()),
				new StructField("accountTypeN", DataTypes.IntegerType, false, Metadata.empty()),
				new StructField("accountTypeX", DataTypes.StringType, false, Metadata.empty()) };

		StructType accountDetailsStructType = new StructType(accountDetailFields);

		ArrayType accountDetailsArray = new ArrayType(accountDetailsStructType, true);

		StructField[] structFieldAccount = new StructField[] {
				new StructField("accountDetail", accountDetailsArray, true, Metadata.empty()) };

		StructType account = new StructType(structFieldAccount);

		StructField[] metadataFields = new StructField[] {
				new StructField("clientId", DataTypes.StringType, false, Metadata.empty()),
				new StructField("registrationNum", DataTypes.IntegerType, false, Metadata.empty()),
				new StructField("numberOfAccts", DataTypes.StringType, false, Metadata.empty()),
				new StructField("account", account, false, Metadata.empty()) };

		StructType metadata = new StructType(metadataFields);

		StructField[] companyFields = new StructField[] {
				new StructField("shortName", DataTypes.StringType, false, Metadata.empty()),
				new StructField("companyIdNum", DataTypes.IntegerType, false, Metadata.empty()),
				new StructField("companyIdStr", DataTypes.StringType, false, Metadata.empty()) };

		StructType company = new StructType(companyFields);

		StructField[] rootFields = new StructField[] {
				new StructField("id", DataTypes.IntegerType, false, Metadata.empty()),
				new StructField("company", company, false, Metadata.empty()),
				new StructField("metadata", metadata, false, Metadata.empty()) };

		StructType root = new StructType(rootFields);

		return root;
```

the reason being i want to define my own encoder and create json with my different attribute.

using the encoder with schema generated i am getting below error.

> Exception in thread "main" org.apache.spark.sql.AnalysisException: No such struct field companyIdNum in SHORT_NAME, COMPANY_ID_NUM, COMPANY_ID_STR;

and default json generated looks something like this.

> {
>    "ID":1,
>    "COMPANY":{
>       "SHORT_NAME":"FOO INCORP",
>       "COMPANY_ID_NUM":0,
>       "COMPANY_ID_STR":""
>    },
>    "METADATA":{
>       "CLIENTID":"",
>       "REGISTRATION_NUM":"",
>       "NUMBER_OF_ACCTS":1,
>       "ACCOUNT":{
>          "ACCOUNT_DETAIL":[
>             {
>                "ACCOUNT_NUMBER":"000000000000001100220033",
>                "ACCOUNT_TYPE_N":0,
>                "ACCOUNT_TYPE_X":""
>             }
>          ]
>       }
>    }
> }

i want json generated with camel case and want to assign the data to custom encoder (MainframeRecord in the same example above). is it any way possible. 

should i post this kind of questions on stackoverflow or here? i am not sure where to post

**Comment by yruslan** [comment]
Cobrix does not support specifying a Spark schema explicitly. But you can manually rename fields of the resulting dataframe. This might be the easiest thing to do in your case.
_(the example is in Scala)_
```scala
    val newDataset = dataset.select(col("id").as("id"),
      struct(
        col("SHORT_NAME").as("shortName"),
        col("COMPANY_ID_NUM").as("companyIdNum"),
        col("COMPANY_ID_STR").as("companyIdStr")
      ).as("company")
    )
...
```

**Comment by plreddy** [comment]
thanks , it works except that i need to do 

> col("COMPANY.SHORT_NAME").as("shortName")

in place of 

> col("SHORT_NAME").as("shortName")
