### ISSUE TITLE
custom format variable length records 

### ISSUE THREAD

**Issue by tr11** [AbsaOSS/cobrix#237]
I have a few files that have the following format

```
      01 RECORD
         02 RECORD-TYPE-ID            PIC X(10).
         02 RECORD-TYPE-1.
            ......
         02 RECORD-TYPE-2.
            ......
```
Depending on the value of `RECORD-TYPE-ID` the record will contain either `RECORD-TYPE-1` or `RECORD-TYPE-2`.  Note that records are not necessarily of the same length and may contain `OCCURS` clauses that cause the record size to be unknown before reading it.

I was thinking that the best approach would be to define a new Header Parser, say `RecordHeaderParserLeadingField` that reads the first few bytes of the record and decides which one is the right segment.  My question is what should I output as a result of the `getRecordMetadata` function. Is an upper bound on the record size enough or do I need the exact record size?

**Comment by yruslan** [comment]
Form the way the use case is described the simplest solution might be:
```
      .option("segment_field", "RECORD-TYPE-ID")
      .option("redefine_segment_id_map:0", "RECORD-TYPE-1 => AAAA1")
      .option("redefine-segment-id-map:1", "RECORD-TYPE-2 => AAAA2")
```
Where 'AAAA1' and 'AAAA2' are values of `RECORD-TYPE-ID` fo eact type of record. Does this approach work for you?

The custom record header parser is also is a good option, especially if many values of `RECORD-TYPE-ID` map to the same record ids. The `getRecordMetadata()` method should return the size of the actual record. So the exact size should be known at that point.

**Comment by tr11** [comment]
That's what I thought I was doing, except that I had a typo on my redefine-segment-id option, hence why I couldn't get it to work. Thanks for your help.

**Comment by yruslan** [comment]
Btw, I forgot to mention. There is this option: `.option("pedantic", "true")`. If turned on, Cobrix won't allow options it does not recognize. This helps with typos.
