### ISSUE TITLE
numeric picture clause with usge display failed

### ISSUE THREAD

**Issue by a4032** [AbsaOSS/cobrix#240]
I've got a picture clause like this
 03 VALUE01    PIC +9999999,99 USAGE DISPLAY.

When reading the file I got this error:
za.co.absa.cobrix.cobol.parser.exceptions.SyntaxErrorException: Syntax error in the copybook at line 23: Invalid input ',' at position 23:46

IS this a correct picture clause ? and if so, how can I read this data with cobrix? 

Thanks

**Comment by tr11** [comment]
Yeah, that's a correct picture clause.  Somehow I didn't add the comma as a valid separator. PR #241 fixes this.
@yruslan, are there any other valid separators? If so, I can add those to the PR before merging.

**Comment by yruslan** [comment]
I never saw decimal separators other than `.` and `.`.

**Comment by yruslan** [comment]
The @tr11 's fix is available in `2.0.2`. It may take some time to get to Maven Central.

Please let us know if it worked for you.

**Comment by a4032** [comment]
thank you very much. 
I've tested it today, and its working. 
just i minor issue with the 'usage display' clause. If the picture is to long, the USAGE  is concatenated at the end of the picture (cfr. 99999U instead of 99999 USAGE.)

**Comment by tr11** [comment]
Could you give a concrete example of a copybook with that behavior?

**Comment by a4032** [comment]
This is a **working** example (partial copy book): 
03 PERC-SE-WN_01      PIC +9999999,99 USAGE DISPLAY.

This one **failed** example (partial copy book): :
03 FFG-BV-SECUREX                 PIC +9999999999999999,99 USAGE DISPLAY.

with error : 
(ef.length:,1)line 7:65 no viable alternative at input '+9999999999999999,99U'
za.co.absa.cobrix.cobol.parser.exceptions.SyntaxErrorException: Syntax error in the copybook at line 7: Invalid input 'U' at position 7:71

**Comment by tr11** [comment]
The issue is not with the parser but with the copybook:

> za.co.absa.cobrix.cobol.parser.exceptions.SyntaxErrorException: Syntax error in the copybook at line 7: Invalid input 'U' at position 7:71

The typical rules for COBOL copybooks apply to this library by default; any character on positions 1-6 and 72+ are considered comments. You may want to deactivate that by using
```
.option("truncate_comments", "false")
```
or by manually editing your copybook so no relevant definitions are on columns 72+.

What's happening in your case is that the `SAGE DISPLAY` portion is stripped as it's past column 72, so the copybook only sees the `+9999999999999999,99 U` part.

**Comment by a4032** [comment]
yes, indeed. That part I had forget. You're completely right. Sorry for the effort on this. 
I will correct my copybook. 
thanks.
