### ISSUE TITLE
Incorrect characters in X fields leads to mixing up columns values

### ISSUE THREAD

**Issue by a4032** [AbsaOSS/cobrix#246]
When you have input data for ex. an ASCII files, but with incorrect characters. The interpretation of the byte is wrong, and this lead to chacater position mismatch in the structure interpretation. 
This is a stragne behaviour, because it is an alphanumeric field X(..), and should be interpreted asis. Leaving the same byte as incorrect byte, without expaning the byte length. 

This is an example: 
data line contains: 'DEVRAIT � TRIMESTRIEL'
copy book line is: '       03 DESCRIPTION PIC X(50). 
Interpreted as 'DEVRAIT     TRIMESTRIEL'  --> 2extra bytes

## Expected behaviour
leaf it as is:'DEVRAIT � TRIMESTRIEL'

The process may not change the content. rubbish in/rubbish-out.  Specially for text columns.

Is there a work-arround for this or need it to be fixed ? 
Thanks

**Comment by a4032** [comment]
the interpreded info is not correct : 
Interpreted as 'DEVRAIT<space><something><something>><something><space>TRIMESTRIEL' --> 2extra bytes

Interpretation with notepad++ , indicated the same:
text:D E V R A I T   �       T R I M E S T R I E L
hex:4445565241495420EFBFBD205452494D4553545249454C

**Comment by a4032** [comment]
meanwhile, some detail found on the input file. 
Data is original: DEVRAIT ê TRIMESTRIEL
File is in codepage Cp1252. 
when reading it in spark with codepage Cp1252, it works fine : ê with hex code 0xea , what is correct.
I've used options in pyspark :
.option("encoding", "ascii")
.option("ascii_charset", "Cp1252")

This results in a movement by 1 position on that characeter ê. And displayed as 'blanco' 
The rest of the data is incorrect split. 
I think the codepage Cp1252 is not well integrated. 
Can you verify urgently please?

**Comment by yruslan** [comment]
Thanks for the bug report. 'cp1252' is not yet supported by Cobrix.
Try
```
.option("ascii_charset", "ISO-8859-1")
```
It might be a compatible charset.

**Comment by a4032** [comment]
Thanks for the answer, but I already tested that one, and is also not complient. 
Any idea when this can be implemented? 
Or is it possible to integrate also the concept of 'garbage-in'/'garbage-out' . So we avoid the extra byte generation?

**Comment by yruslan** [comment]
Just checked - `cp1252` works as expected. Could you please attach a small data file and a copybook so we could reproduce the issue? I'd also ask for a small code snippet to make sure we understand the exact way you are loading the data.

The garbagi-in/grabage-out idea won't work since conversion from byte arrays to strings need s to happen. And this can be done only if we know the exact encoding of the input data.

**Comment by a4032** [comment]
unfortunattely, I can't send you the data (GDPR related data) So I'm not allowed. 
I'll need to make a special test file to do this. 
But if you test cp1252, how is it possible that you don't get the extra byte for characters like ê ? 
Strange, what am I missing here...
I'll try to make a small test file and script today

**Comment by yruslan** [comment]
> I'll try to make a small test file and script today

Thank you. This will definitely help to speed things up.

> But if you test cp1252, how is it possible that you don't get the extra byte for characters like ê ?

This character takes one byte in cp1252. And it is converted into a single character on the output string. Nothing is added or removed. Yeah, the test case will definitely clear things up.

**Comment by a4032** [comment]
Yruslan, 
Sorry for the lost time, but I found the issue. It is NOT in Cobrix, but a part of the preprocessing steps just before. 
It's related to unzippin file process, because Cobrix could work with .zp files. 
The unzip process by spark works fine, but writing back to unzip textfiles has issues. This step add's one extra byte. 
The input for the cobrix process part was by that an incorrect input file. 
Sorry for the lost time on investigating this.
On the other hand, maybe a new feature to read from compressed GZIP files?

**Comment by yruslan** [comment]
No worries. 😄  Glad you've found the issue. 

The issue with gzip is that it is an unsplittable. So far we don't have plans to support it in Cobrix.
