### ISSUE TITLE
Can we set default value for a column with possible empty value?

### ISSUE THREAD

**Issue by chandrasekaravr** [AbsaOSS/cobrix#247]
## Background [Optional]
I have a multi-segment file and its copybook has the redefines specified. With a common group at the top containing the segment attributes. Even though there are distinct values for an attribute in the common segment, that is used to identify the resegment and to pick the redefine group, it also has empty value for a specific record or segment type. How can we resegment based on this empty value? If a default value can be assigned upon parsing, we can use that that to resegment

## Question
* Is it possible to set default value for any attribute/field? or use _impliedDefaultValue_ specified in the copybook?
* Alternately, is it possible resegment and use a redefined group based on empty value or assign a default redefine group, if a matching resegment value is not present? 
For example, in this mapping, 
```
      .option("redefine_segment_id_map:0", "RECORD_GRP_1 => ")
      .option("redefine_segment_id_map:1", "RECORD_GRP_2 => A")
      .option("redefine-segment-id-map:2", "RECORD_GRP_3 => B")
      .option("redefine_segment_id_map:3", "RECORD_GRP_4 => X")
      .option("redefine_segment_id_map:4", "RECORD_GRP_5 => Y")
```
has 
`.option("redefine_segment_id_map:0", "RECORD_GRP_1 => ")` empty value to match

**Comment by yruslan** [comment]
Thanks for such a detailed feature request!
We'll take a look. I think we need to add special support for such a case.

**Comment by chandrasekaravr** [comment]
@yruslan Thanks Ruslan. I understand, i will wait for it.

**Comment by yruslan** [comment]
@chandrasekaravr , it seems that empty segment ids are supported and can be used exactly as you described.
You can take a look at this unit test: https://github.com/AbsaOSS/cobrix/pull/250/files
Please, let me know if it covers your use case.

**Comment by chandrasekaravr** [comment]
@yruslan Thanks. Will try it out.
