### ISSUE TITLE
Parsing a variable length multi-segment file with No RDW

### ISSUE THREAD

**Issue by chandrasekaravr** [AbsaOSS/cobrix#248]
## Background [Optional]
I have VB multi-segment file with no RDW. However, each record/segment starts with a Char identifier to identify the segment. I wrote a CustomRecordHeaderParser(with header length 1)  to check this character and return the expected record length for that record/segment.

The VarLenNestedIterator is not including the header bytes as part of record bytes and returns only the next set of bytes corresponding to record length as returned in RecordMetadata by the CustomRecordHeaderParser.

## Question
How can we instruct the parser to include the header bytes in the record bytes?
I tried with `.option("record_start_offset", "-1")` and it failed with the error, we cannot give negative offset. Can this be somehow used with `rdw_adjustment`

**Comment by yruslan** [comment]
Thanks for the question! This is an easy one 😄 
The record header parser interface has a method called `isHeaderDefinedInCopybook`. If it returns true, the header itself (the character in your case), will be returned.
```scala
  /**
    * If true the record parser will expect record headers to be defined in the copybook itself.
    * If false the headers are not expected to be defined in the copybook and the number of bytes
    * returned by `getHeaderLength` will be truncated before record bytes are passed to the parser.
    */
  def isHeaderDefinedInCopybook: Boolean
```

**Comment by chandrasekaravr** [comment]
Thanks @yruslan. I misunderstood this field, earlier. It worked perfectly.
