### ISSUE TITLE
Calculation of data width

### ISSUE THREAD

**Issue by schaloner-kbc** [AbsaOSS/cobrix#263]
I have a copybook (can't post for security reasons, but it has a lot of PIC N fields and some redefines.  The length of the data is not exactly divisible by the data width calculated by Cobrix, and so can't be parsed.  I have validated the data separately and it's fine.

Is there a reason the data width is not equal to the sum of the bytes (byte * 2 in the case of PIC N)?

**Comment by yruslan** [comment]
The record size should be exactly the sum of bytes of each field (num. of characters *2 in case of N).

You can parse a copybook and print layout of fields. This might help you investigate.
```scala
    val cobolSchema = CopybookParser.parseTree(copybookContents)
    println( cobolSchema.generateRecordLayoutPositions() )
```

**Comment by schaloner-kbc** [comment]
Thanks @yruslan using this I can see the first field of a redefine is being skipped.  I'll try to isolate it in the code and patch.
