### ISSUE TITLE
Segment Redefine, space

### ISSUE THREAD

**Issue by tr11** [AbsaOSS/cobrix#267]
I have a file with two segments tied to a field that can take two possible values: " " and "X".
I may be missing something simple, but how do I pass that space " " to the redefine option

```.option("redefine_segment_id_map:0", "SEGMENT1 => ?")```

**Comment by tr11** [comment]
Actually, it seems that passing ` .option("segment_id_level0", "")` and using 
```.option("redefine_segment_id_map:0", "SEGMENT1 => ")``` works fine.  Is this the intended way to specify a empty string?

**Comment by yruslan** [comment]
Yes, this is the intended way. If you find it counter-intuitive, we can add additional ways to do it.
Maybe:
```
.option("redefine_segment_id_map:0", "SEGMENT1 => '' ")
```
?

**Comment by tr11** [comment]
No need for it -- it works fine as is. Maybe I'll add a note to the docs if that's fine with you.

**Comment by yruslan** [comment]
> Maybe I'll add a note to the docs if that's fine with you.

You are always welcome. It is completely up to you.
