### ISSUE TITLE
Applying SparkUtils.flattenSchema() method in PySpark

### ISSUE THREAD

**Issue by eapframework** [AbsaOSS/cobrix#272]
Hi, After reading mainframe file into Spark dataframe, I was planning to flatten the nested datatypes using SparkUtils.flattenSchema() method.
Since i am programming in pyspark, _import _za.co.absa.cobrix.spark.cobol.utils__ is throwing an error message.

 Please advise whether it is possible to apply SparkUtils.flattenSchema() method in pyspark?

I tried below code

`df = DataFrame(sparkCont._jvm.za.co.absa.cobrix.spark.cobol.utils.SparkUtils.flattenSchema(df._jdf),sqlContext)`

But getting below error

> py4j.protocol.Py4JError: An error occurred while calling z:za.co.absa.cobrix.spark.cobol.utils.SparkUtils.flattenSchema. Trace: py4j.Py4JException: Method flattenSchema([class org.apache.spark.sql.Dataset]) does not exist

Thanks!

**Comment by yruslan** [comment]
Thanks for the question. Unfortunately, we don't know the answer. All our use cases are Scala-based so we don't use PySpark.

The `flattenSchema` method is a pure library method and it is not part of Spark. If there is something we can do from our side to allow this method to be used from PySpark, please let us know.

**Comment by eapframework** [comment]
Hi Yruslan, I was able to call `flattenSchema `method using below code

`df_mfdata = DataFrame(sparkCont._jvm.za.co.absa.cobrix.spark.cobol.utils.SparkUtils.flattenSchema(df._jdf, `True),sqlContext)``

There is an issue in py4j, we cannot skip default arguments when calling scala method.

**Comment by yruslan** [comment]
Great, good to know. Thanks!
