### ISSUE TITLE
How to parse copybook having occurs

### ISSUE THREAD

**Issue by PratapaSubramanyam** [AbsaOSS/cobrix#281]
I have a copy book in which a group occurs 12 times. how do i parse this ?
is there any option i need to use ?
sample is below
05  IT-CA-MONTHLY-SEGMENT             OCCURS 12 TIMES.
                    10  IT-CA-DATE-EOM                PIC 9(08)  COMP-3.
                    10  IT-CA-BLOCK-CODE              PIC X(03).

**Comment by yruslan** [comment]
This should parse automatically with default options. Let me know if you experience issues or error messages.

**Comment by PratapaSubramanyam** [comment]
Hi,

I am albe to parse it but not able to split it. i need 12 copies of DATE_EOM and BLOCK_CODE. How do i split this array into 12 copies of both the columns. Hope my question makes sense.
![image](https://user-images.githubusercontent.com/39309013/80345141-f95fc180-8868-11ea-89e1-5b7fb981590b.png)

**Comment by yruslan** [comment]
The OCCURS statement has been parsed as a Spark nested array. Each record will have 12 elements in this array in your case. So all inner values of the GROUP are there as a nested struct.

You can make each array element a separate column by flattening the schema:
```scala
val dfFlattened = SparkUtils.flattenSchema(dataFrame)
```
This is a purely Spark routine, not Cobol-specific. We added just as an example of what you can do in Spark.

**Comment by PratapaSubramanyam** [comment]
thank you so much
