### ISSUE TITLE
streaming

### ISSUE THREAD

**Issue by mpisu** [AbsaOSS/cobrix#29]
I'm reading a file in streaming I have no error the count returns 0

 my code 

  
    val spark = SparkSession
      .builder()
      .appName("CobolParser")
      .master("local[2]")
      .config("duration", 13)
      .config("copybook", paramMap("-Dcopybook"))
      .config("path",paramMap("-Ddata") )
     .getOrCreate()
     val streamingContext = new StreamingContext(spark.sparkContext, Seconds(13))
    import za.co.absa.cobrix.spark.cobol.source.streaming.CobolStreamer._
    val reader = getReader(streamingContext)
   val result = streamingContext.cobolStream()
    result.foreachRDD( (rdd:RDD[Row],time: Time) => {
      println(time)
      println(rdd.count())
      for(item <- rdd) {
        println(s"---------------${item}")
      }
    })

output  example : 
9/01/13 09:30:47 INFO JobScheduler: Added jobs for time 1547400647000 ms
19/01/13 09:30:47 INFO JobScheduler: Starting job streaming job 1547400647000 ms.0 from job set of time 1547400647000 ms
1547400647000 ms
19/01/13 09:30:47 INFO SparkContext: Starting job: count at NewStreamingEbcdic.scala:78
19/01/13 09:30:47 INFO DAGScheduler: Job 0 finished: count at NewStreamingEbcdic.scala:78, took 0.005128 s
**0**
19/01/13 09:30:47 INFO SparkContext: Starting job: foreach at NewStreamingEbcdic.scala:79
19/01/13 09:30:47 INFO DAGScheduler: Job 1 finished: foreach at NewStreamingEbcdic.scala:79, took 0.000039 s
19/01/13 09:30:47 INFO JobScheduler: Finished job streaming job 1547400647000 ms.0 from job set of time 1547400647000 ms
19/01/13 09:30:47 INFO JobScheduler: Total delay: 0.252 s for time 1547400647000 ms (execution: 0.085 s)
19/01/13 09:30:47 INFO FileInputDStream: Cleared 0 old files that were older than 1547400582000 ms: 
19/01/13 09:30:47 INFO ReceivedBlockTracker: Deleting batches: 
19/01/13 09:30:47 INFO InputInfoTracker: remove old batch metadata: 
19/01/13 09:31:00 INFO FileInputDStream: Finding new files took 11 ms
19/01/13 09:31:00 INFO FileInputDStream: New files at time 1547400660000 ms:

because ????

**Comment by felipemmelo** [comment]
@mpisu , a couple of questions:

1. Did you have new files in your directory that would be detected by Spark streaming engine? The log says **Cleared 0 old files**

2. If you were adding files to the directory, did you tell Spark to wait for the streaming job termination?
