### ISSUE TITLE
Does Cobrix 2.0.7 can be used with Spark 2.2 and 2.3

### ISSUE THREAD

**Issue by chanduhawk** [AbsaOSS/cobrix#302]
Does Cobrix 2.0.7 can be used with Spark 2.2 and 2.3 ? In the user guide its mentioned Cobrix 2+ supports Spark 2.4 + 

But still I am able to use cobrix  2.0.7 can be used with Spark 2.2. Please let me know if there is any difference ?

**Comment by yruslan** [comment]
Cobrix should work fine on Spark 2.2 and maybe even earlier versions. It just we haven't tested it on versions older than 2.4.3.

In general, Cobrix implements high-level interfaces of Data Source API v1. This existed throughout Spark 2.x. So it should work fine. But Spark's dependencies changed a lot during the evolution of 2.x, so binary incompatibilities are possible.

From our side, we'd suggest you can use it for Spark 2.2 and it will work. But if you encounter a binary incompatibility (ClassNotFoundException, MethodNotFoundException, etc), try getting the sources, changing Spark dependencies to the particular version, and compiling it. Please, let us know if you have any issues.

**Comment by chanduhawk** [comment]
Thanks a lot, it was working for us but just wanted to get confirmation for any issues
