### ISSUE TITLE
Move CobolRelation to a shared library?

### ISSUE THREAD

**Issue by schaloner-kbc** [AbsaOSS/cobrix#307]
## Background
As part of our ongoing efforts to trace lineage using Spline, we have come across the need to handle CobolRelations.

## Question
CobolRelation is currently part of cobrix, so spline-user-agent would require cobrix as a dependency to handle this type.  

Would it be possible to move CobolRelation into a new library that both cobrix and spline-user-agent would have as a dependency?

**Comment by schaloner-kbc** [comment]
Requires way too much refactoring, I think this is a non-starter.

**Comment by yruslan** [comment]
Hi, I think Spline is adding support for Cobrix specifically. You might want ask at their project space.
