### ISSUE TITLE
RDW interpretation is incorrect for an IBM z/OS dataset

### ISSUE THREAD

**Issue by rwelk1201** [AbsaOSS/cobrix#31]
Record Descriptor Word (previously referred to as XCOM header) is interpreted incorrectly for a file transferred from IBM z/OS to Windows 10 via standard FTP in binary mode. 

Per the IBM documentation (https://www.ibm.com/support/knowledgecenter/en/SSLTBW_2.3.0/com.ibm.zos.v2r3.idad400/d4357.htm) the RDW is the first 2 bytes of each record, but the extractRdwRecordSize method in the BinaryUtils class is expecting the length to be in the 3rd and 4th bytes.

It's possible XCOM or other transfer methods change the interpretation of the RDW, but the current method makes it impossible to process a dataset originating from IBM z/OS, at least in our environment. 

I am able to process the datasets correctly by making a minor adjustment to the extractRdwRecordSize method to read the 1st and 2nd bytes, and the data is parsed correctly after that.

**Comment by yruslan** [comment]
Opened a PR https://github.com/AbsaOSS/cobrix/pull/36

**Comment by yruslan** [comment]
@rwelk1201, we'd appreciate if you could take a look at the PR and let know if this is what you are looking for.
