### ISSUE TITLE
Getting ClassNotFoundException for cobol.DefaultSource

### ISSUE THREAD

**Issue by kanika167** [AbsaOSS/cobrix#311]
## Background [Optional]
Trying to Run a simple program to read data in cobol into a dataframe. Have included all the necessary dependencies in gradle.build file. Also tried to pass fat jar with spark submit.

## Question
Even after passing a fat jar, still Getting ClassNotFoundException for cobol.DefaultSource

**Comment by kanika167** [comment]
https://github.com/AbsaOSS/cobrix/issues/1

This issue helped. You need to set za.co.absa.cobrix.spark.cobol.source in source as format while creating a data frame

**Comment by yruslan** [comment]
Yes, it is one of the solutions. Also, if you are creating an Uber jar you need to make sure to use service merger transformer: https://github.com/AbsaOSS/cobrix/blob/5fc8d420d4fa4fd96ae8c93b8d4f04cd2795bd76/examples/examples-collection/pom.xml#L118

Then, you'll be able to use the short name of the data source.
