### ISSUE TITLE
Do we have any other schema retention policy other than collapse_root.

### ISSUE THREAD

**Issue by chanduhawk** [AbsaOSS/cobrix#314]
## Background [Optional]
A clear explanation of the reason for raising the question. 
This gives us a better understanding of your use cases and how we might accommodate them.

## Question
I want to collapse one level down to the root. Can I do that using cobrix.

**Comment by yruslan** [comment]
The `collapse_root` schema retention policy does exactly that.

Can you provide an example of how it currently works and what do you want to achieve,

**Comment by chanduhawk** [comment]
For example I have a copybook like below

01 Record_details
    05 FirstName PIC A(4)
   05  Address PIC X(40)
      10 Addr1 PIC X(10)
      10 Addr2 PIC X(30)

if we are going to use collapse root it will ignore the level 01 now. But for example I want to collapse 05 Address PIC X(40) so I will ignore all 05 level other than this field.

expected output
Addr1 Addr2

**Comment by chanduhawk** [comment]
Any update on this please

**Comment by yruslan** [comment]
We don't have plans for collapsing more than 1 level at the moment.
But you can use a flattening tool if you want a flat schema (in order to export to CSV perhaps).
```scala
val df: DataFrame = ???
val dfFlat = SparkUtils.flattenSchema(df)
dfFlat.printSchema()
```

**Comment by chanduhawk** [comment]
Thanks, will try that approach
