### ISSUE TITLE
Leveraging copybookparser in java

### ISSUE THREAD

**Issue by chanduhawk** [AbsaOSS/cobrix#315]
I want to use below copybookparser for retrieving sparksql schemas in java.

val parsedSchema = CopybookParser.parseTree(copyBookContents)

in Java its expecting all the parameters for parseTree function. Please let me know how to resolve it using java code

**Comment by yruslan** [comment]
New versions of Cobrix have `CopybookParser.parse()` method. Try using it. The only mandatory parameter is cookbook content.

**Comment by chanduhawk** [comment]
We tried with V2.1.0, but still its expecting all the parameters.

**Comment by chanduhawk** [comment]
We tried with V2.1.0, but still its expecting all the parameters.

**Comment by yruslan** [comment]
I can implement something line `parseDefault()` that won't require parameters. Could I ask you to post the piece of code you use to parse a copybook now? I want to double-check the values that you pass.

**Comment by chanduhawk** [comment]
I am just trying to provide only copybook content as the parameter so that i can get the parsed schema.

**Comment by yruslan** [comment]
Will add `parseSimple()` that will require just a couple of arguments that are copybook and AST-related.

**Comment by chanduhawk** [comment]
Thanks sure.

**Comment by chanduhawk** [comment]
Its already released but didnt find it in Maven. Please check once

**Comment by yruslan** [comment]
It's already deployed. We merge release PRs when we see the artifact on Maven Central. 
It is there already: https://search.maven.org/artifact/za.co.absa.cobrix/spark-cobol_2.11/2.1.1/jar

**Comment by chanduhawk** [comment]
Yes thats what i thought. But Please check maven repo https://mvnrepository.com/artifact/za.co.absa.cobrix/spark-cobol

its not updated yet.

**Comment by chanduhawk** [comment]
its my bad, there was a typo on my end while i procure it in our space.
