### ISSUE TITLE
Add support for nested segment loading

### ISSUE THREAD

**Issue by yruslan** [AbsaOSS/cobrix#33]
Currently multisegment files can be loaded one segment in time. It might be very useful to add a possibility to load all the segments of a hierarchical database. Children nodes can became an array of struct inside root node.

Open implementation questions:

- How should users specify parent-child relationships among segments? Perhaps need to specify parent segment for each segment.
- How should users provide schema for each of the segments? Should a copybook per segment be required or we can somehow combine all segments in one copybook? Which is better?

**Comment by tr11** [comment]
This would be great.  I have a few files with multiple segments (with many copybooks!). Being able to specify multiple copybooks would be fantastic.

Would this work together with the [custom header](https://github.com/AbsaOSS/cobrix/tree/feature/68-allow-custom-rec-header-parsers) branch?  The only issue I see with that is the variable record length is any of the copybooks has an OCCURS DEPENDING ON clause.

**Comment by yruslan** [comment]
Yeah, completely agree. This could be a very good feature. And, of course, it will be compatible with custom record header parsers.
