### ISSUE TITLE
za.co.absa.cobrix.cobol.parser.exceptions.SyntaxErrorException: Syntax error in the copybook at line 515: Invalid input 'POINTER' at position 515:59

### ISSUE THREAD

**Issue by jianyu0503** [AbsaOSS/cobrix#353]
I am trying to load a mainframe bin file into a dataframe. 
```python
dataframe   = (spark.read.format("cobol")        
          .options    (copybook = copybook) 
          .option     ("is_record_sequence", "true")
          .option     ("rdw_adjustment", 4)	
      .load(datafile))
```
Most of files can be loaded properly but only when "USAGE IS POINTER." is showing up in one line of copybook file, it throws an error called "
za.co.absa.cobrix.cobol.parser.exceptions.SyntaxErrorException: Syntax error in the copybook at line 515: Invalid input &#39;POINTER&#39; at position 515:59". How can we handle this error when reads the cobol file?

**Comment by yruslan** [comment]
Yes, `USAGE IS POINTER` is not supported. What's the full definition of that field?

**Comment by jianyu0503** [comment]
Thank you @yruslan! I am new to the mainframe and what i know is that USAGE IS POINTER stores the address rather than data but i maybe wrong,
