### ISSUE TITLE
Fix code duplication for COBOL AST

### ISSUE THREAD

**Issue by yruslan** [AbsaOSS/cobrix#37]
Currently COBOL AST is an array of GROUP objects. Need to change it to be just a GROUP. This way AST traversal functions can be simplified.
Also, this can allow root level primitive fields in copybooks.

This is to support something like
```
     05 FILLER PIC 9(08) BINARY.
     05 :RRHEADER:-CNTL.
        10 :RRHEADER:-LENGTH PIC S9(08) BINARY.
           88 :RRHEADER:-LENGTH-SET VALUE +65.
```
The filler on the top is not currently supported since it is a primitive field.

**Comment by tr11** [comment]
Is this handled by #79?

**Comment by yruslan** [comment]
Yes, it is indeed.
