### ISSUE TITLE
Copybook without 01 or root record

### ISSUE THREAD

**Issue by codealways** [AbsaOSS/cobrix#396]
## Background
Though root record with 01 level is mandatory, can cobrix handle copybook without 01 level

## Feature
Having feature where cobrix can read copybook without root or 01 level. It would check the presence of 01 record and if it's not available then it should consider as ignoring the root level like the schema_retention_policy to collapse_root. If user has provided schema retention policy to collapse_root then even if root record is not available still we should consider the root record as implicit and not to fail the code.
## Proposed Solution [Optional]
Solution Ideas 
1. 
2. 
3.

**Comment by yruslan** [comment]
Thanks for raising the issue! I had exactly the same idea :)

We are going to implement it exactly like this.
