### ISSUE TITLE
Multiple copybooks null values

### ISSUE THREAD

**Issue by MaksymFedorchuk** [AbsaOSS/cobrix#405]
Let's say we have 2 copybooks and file with data
1st is :
 01  AAA  .
       05 BBB   PIC X.
2nd is:
01 CCC  .
     05  DDD   PIC X.  
file with data:
g
p
c
input_DF = spark.read.format("cobol") \
            .option("is_record_sequence", "true") \
            .option("is_text", "true") \
            .option("encoding", "ascii") \
            .option("copybooks", copybook_1,copybook_2) \
            .load(file)
then in dataframe I will have column AAA.BBB having values g,p,c for each record respectively and CCC.DDD having values null,null,null. My expectation is that both columns should have g,p,c values.

**Comment by yruslan** [comment]
This is interesting. Thanks for reporting! Will check

**Comment by yruslan** [comment]
This issue is related to the fact the Cobrix currently doesn't support redefines on the top level. There is a workaround but I'm keen to fix it.
