### ISSUE TITLE
Handle nullable byte field

### ISSUE THREAD

**Issue by jordanstoilov** [AbsaOSS/cobrix#413]
## Background [Optional]
In the file coming from the mainframe, there is an additional byte in front of every field which is nullable. Cobrix can not detect this byte in the process of parsing, because this is missing in the description(copybook). One approach would be to edit the description adding FILLER field just before the nullable field, then cobrix by default will skip it. 

## Question
Is there a more elegant solution using cobrix options for solving this issue? I read the documentation, but it is possible that I have missed something.

**Comment by yruslan** [comment]
Hi, this is something new, we haven't encountered this way of representing nullability. Using fillers is a good solution, but we are happy to also add direct support of such nullable fields. Could I ask you to provide an example of such data and a copybook to serve as a requirements definition? A synthetic example is sufficient.

**Comment by jordanstoilov** [comment]
Hello, unfortunately, I could not send you an example, because of the sensitivity of the data. I have a dumped files from the mainframes and I don't have access to it as well, so I could not provide you synthetic example also. What I can do is to describe to you, how you can reproduce the issue. During the process of creating a new file declare some fields that could have a null value.
![image](https://user-images.githubusercontent.com/30410230/130029116-39b864df-6646-4d60-9e82-99d74b50337a.png)
Generate copybook and get data file. When you read it using cobrix, you will get an IllegalArgumentException with a message "There are some files in ... that are NOT DIVISIBLE by the RECORD SIZE calculated from the copybook (93 bytes per record). Check the logs for the names of the files." This exception is caused by a missing description in the copybook about whether some field is nullable or not. If you open the data file in some hex editor you will see, that in front of every nullable field there is an additional byte.

**Comment by yruslan** [comment]
Hi, sorry I don't have access to a mainframe system that supports nullable fields. Unless we have an example or a spec on how null values are represented in the data file we don't have enough information in order to implement it.

A simplest synthetic example that would be sufficient is a copybook with a data file that contains only 1 nullable field, and 2 records, one null, other non-null. I think sensitive-data free example like this could be created in a HEX editor from the data you already have.

**Comment by jordanstoilov** [comment]
Hello, I am sending files.
[data.zip](https://github.com/AbsaOSS/cobrix/files/7014383/data.zip)
AFDI and DATUM are declared as nullable.

**Comment by yruslan** [comment]
Thanks for the example!
Looking into the original copybook (without fillers), and it seems nullable fields are not marked in any way so the parser can't tell if a field is nullable or not. So it seems adding fillers or extra fields in the copybook is the only way i can see this can be solved. Please, let me know if you have ideas how this can be automated.

**Comment by jordanstoilov** [comment]
Hello, yes they are not, I mentioned it from the beginning. As a workaround, I will change the copybook content for this kind of field programmatically. But I don't have any idea, how this could be automated in cobrix.
Thanks for your support!

**Comment by jordanstoilov** [comment]
At the moment there is no automated solution for these fields being caught and this extra byte to be parsed.
