### ISSUE TITLE
Cobrix throwing error when copybook has fieldname ends with '-'

### ISSUE THREAD

**Issue by Loganhex2021** [AbsaOSS/cobrix#427]
## Describe the bug
In Databricks throwing error, when reading ebcdic file using cobrix with fieldname ends with '-' on the copybook.

## To Reproduce
For Example, in the copybook

FieldName1  PIC X95).
FieldName2- PIC X95).

## Expected behaviour
It should able to read the file with out error.

**Comment by yruslan** [comment]
What error are you getting? Will try to reproduce on local Spark
