### ISSUE TITLE
special characters not supported in ebcdic file

### ISSUE THREAD

**Issue by krahul19091992** [AbsaOSS/cobrix#441]
I am consuming an ebcdic file in spark cobrix but when checking the dataframe the special characters are replaced by blanks

is there any option in the package to specify the charset/encoding for ebcidic like its there for ascii

note - the file is in ebcdic format

**Comment by yruslan** [comment]
You can use 
```
.option("ebcdic_code_page", "common")
```
Specifies a code page for EBCDIC encoding. Currently supported values: `common` (default), `common_extended`, `cp037`, `cp037_extended`, `cp875`. `*_extended` code pages supports non-printable characters that converts to ASCII codes below 32.

If the EBCIDIC code page is neither 'common' nor `cp037`, there is a way to define a custom code page. Or you can refer to the code page you are using, and we can add support for it.

**Comment by krahul19091992** [comment]
thanks a lot it worked  - option("ebcdic_code_page", "cp037")
