### ISSUE TITLE
Java ClassNotFoundException when class is present in .Jar file used on AWS Glue

### ISSUE THREAD

**Issue by tad8zd** [AbsaOSS/cobrix#448]
## Background
Hello,

I am trying to use Cobrix within AWS Glue and uploaded the dependencies/required Jars into an S3 bucket and currently running an AWS Glue Scala script to process a copy book & mainframe data file. I tried a combination of different versions but keep getting the same error when I try to export the file to a parquet.

Error Message:
Exception in User Class: org.apache.spark.SparkException : Job aborted due to stage failure: Task 0 in stage 0.0 failed 4 times, most recent failure: Lost task 0.3 in stage 0.0 (TID 3) (10.200.100.228 executor 3): java.io.IOException: java.lang.ClassNotFoundException: za.co.absa.cobrix.spark.cobol.source.types.FileWithOrder.

I checked within the Jar and the class FileWithOrder is present within it so I'm not sure what I'm missing here. Any help would be greatly appreciated!

Script Below:

object CobolDataProcessor {
  def main(sysArgs: Array[String]): Unit = {
    val args = GlueArgParser.getResolvedOptions(sysArgs, Seq("JOB_NAME").toArray)
    val spark: SparkContext = new SparkContext()
    val glueContext: GlueContext = new GlueContext(spark)
    Job.init(args("JOB_NAME"), glueContext, args.asJava)
    val df = glueContext.read.format("za.co.absa.cobrix.spark.cobol.source").option("copybook", 
    "s3://cobolfile.cob").option("is_record_sequence", "true").load("s3://sourcebucket")
    val df1 = df.toDF()
    df1.write.mode(SaveMode.Append).parquet("s3://outputbucket")
    Job.commit()
  }
}

**Comment by yruslan** [comment]
Hi, please try `spark.read.format("za.co.absa.cobrix.spark.cobol.source")` instead of `glueContext.read`

Also, how did you get/built the cobrix jar you uploaded as the dependency?

**Comment by tad8zd** [comment]
> Hi, please try `spark.read.format("za.co.absa.cobrix.spark.cobol.source")` instead of `glueContext.read`
> 
> Also, how did you get/built the cobrix jar you uploaded as the dependency?

I changed it to spark and got 'error: value read is not a member of org.apache.spark.SparkContext'

**Comment by yruslan** [comment]
Cool. 

Regarding the error - yes, sorry, I misread. You need a `SparkSession`, not `SparkContext`. I'm sure you can get the Spark session from `glueContext`:
```
val sparkSession = glueContext.getSparkSession
sparkSession.read.format("za.co.absa.cobrix.spark.cobol.source")
``` 

Regarding the uber jar:
The best way to generate an uber jar for integration to Databricks and AWS Glue is by using `sbt assembly`

As per README:
```
sbt ++2.12.15 assembly -DSPARK_VERSION=2.4.8
```
Replace `2.12.15` with the Scala version, and `2.4.8` with Spark that matches Glue.
S3 support should be available automatically by Glue.

**Comment by tad8zd** [comment]
Ah okay I believe we are making progress. I used the sbt assembly and uploaded that compiled .jar and the error has changed to a "Exception in User Class: java.lang.UnsupportedClassVersionError : za/co/absa/cobrix/cobol/parser/antlr/jsonBaseVisitor has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0" Are you aware of how to go about debugging this error?

**Comment by yruslan** [comment]
You need to rebuild the Cobrix jar using JVM 1.8, and not the latest one, since Java runtime on Glue is 1.8

**Comment by tad8zd** [comment]
So I changed my jdk to 1.8 and reassembled it with sbt and it reverted back to my initial error of ClassNotFoundException...

**Comment by tad8zd** [comment]
Turns out my issue was within the Glue parameters themselves. I had to point to the specific jar file in the dependent jars path and use the "--extra-jars" and "--user-jars" = true in order for it to work. Thank you for your help!

**Comment by yruslan** [comment]
Great! 🚀
