### ISSUE TITLE
Upgrading synk?

### ISSUE THREAD

**Issue by milehighhokie** [AbsaOSS/cobrix#449]
For the snyk vulnerability for com.fasterxml.jackson.core:jackson-databind 2.10.3, 
is there a plan to upgrade to com.fasterxml.jackson.core:jackson-databind 2.10.5.1 or higher?

**Comment by yruslan** [comment]
Updated the dependency for converters. The `spark-cobol-s3` example project will be updated later with the move to Spark 3.2.X

**Comment by milehighhokie** [comment]
Thanks Ruslan!!
