### ISSUE TITLE
Hierarchical Datasets prcossing 

### ISSUE THREAD

**Issue by Shaheed818** [AbsaOSS/cobrix#452]
Hi,
trying to use Cobrix solution to process EBCDIC file that has parent and Child records. I need to process them to different hive tables.

parent record is always start with A and will long last for 500 bytes followed by child records called B and C (0 or more occurrences) will long last for 60 bytes.
A.{500}+[B|C].{60} (A is parent record mandatory and B and C or optional in source data with 0 or more occurrences).

Can you answer with below questions?

Can i process about file using .option("record_format", "V")? is this available in 1.x?
how to generate a relationship between parent and child elements - a key can be generated ?
getting below error. what is missing?
spark.read.format("cobol").option("copybook","file:///file.cob").option("schema_retention_policy", "collapse_root").option("truncate_comments", "false").option("generate_record_id", "true").option("is_record_sequence", "true").load("hdfs//file")
Caused by: java.lang.ClassNotFoundException: za.co.absa.cobrix.spark.cobol.source.types.FileWithOrder

using Spark 2.3 version and spark.cobol 1.x

Thanks in advance for your answers.

Regards,

**Comment by yruslan** [comment]
`.option("record_format", "V")` is available only in the latest version (`2.4.5`) and I would encourage using it. You can build the latest Cobrix for Spark 2.3 using `sbt assembly` command mentioned in README.

Cobrix 1.x supports `.option("is_xcom", "true")` for variable record length files. But using the latest Cobrix is preferrable.

**Comment by Shaheed818** [comment]
Hi ,

Thanks for your quick response. I could see the class present in 1.x package. why am i getting below error?

Caused by: java.lang.ClassNotFoundException: za.co.absa.cobrix.spark.cobol.source.types.FileWithOrder

**Comment by yruslan** [comment]
Could be many reasons. I'd advise trying the above suggestion to make 2.4.5 work first.

But if you still want to investigate the 1.x issue, please answer the following:
- Spark/Scala version you are using
- Cobrix exact version
- Code snippet that reads the data
- Form of deployment (uber jar + spark submit, spark shell, AWS Glue, Databricks, etc)

**Comment by yruslan** [comment]
It looks like the file has a variable record length format. If the input file doesn't have RDW headers nor line ending character between records, the only way to decode it is using custom record extractors.

Check 'Custom record extractors' section in README.

It is not trivial to implelent. I can help with that if you provide an example file + a copybook
