### ISSUE TITLE
can Cobrix be used to convert ASCII to EBCDIC?

### ISSUE THREAD

**Issue by manaac** [AbsaOSS/cobrix#455]
Hi, we are using Cobrix to read a Mainframe file by specifying the Cobol copybook and ingesting to HDFS as Parquet file

However we have a requirement to do the reversal i.e. after ingesting a file to HDFS, we wanted to convert that as EBCDIC file and send to Mainframe. 

Does Cobrix support this?

**Comment by yruslan** [comment]
Hi, thanks for your interest in the project. No, writing EBCDIC mainframe files is not supported at the moment. There is a discussion around this, but I'm not sure when we start actually implementing it.
You can track the discussion here: https://github.com/AbsaOSS/cobrix/issues/415
