### ISSUE TITLE
0000{ is converted to null instead of 0 when field type has PIC S9(5) in US_ASCII file

### ISSUE THREAD

**Issue by Loganhex2021** [AbsaOSS/cobrix#459]
## Describe the bug
In Cloud Migration Project, Cobrix library is making null for the field when we get a value like '0000{' to the type PIC s9(5) in copybook for the US_ASCII file.
In the existing on-prem system it was making 0 and not giving null for the same value. 
Could you please help us to solve this

Sample US_ASCII Data:
P0000{
T12340
P89870

CopyBook:
01 Employee.
  05 EmployeeType  PIC X(1).
  05 Salary                PIC S9(5).

Expected Output:
EmployeeType Salary
P                       0
T                       12340
P                       89870

**Comment by Loganhex2021** [comment]
@yruslan - Do you have any comment for this question ?

**Comment by yruslan** [comment]
Looks like a good catch. Will take a look

**Comment by yruslan** [comment]
Hi, I've tried reproducing the bug using a test. And it worked for me:
https://github.com/AbsaOSS/cobrix/blob/bugfix/459-parsing-ofnumerics/spark-cobol/src/test/scala/za/co/absa/cobrix/spark/cobol/source/regression/Test17NumericConversions.scala

What options do you pass to the reader (`spark.read...`)?

**Comment by yruslan** [comment]
Sorry, I see that you have the punched sign, will chek that as well :)

**Comment by yruslan** [comment]
I confirm the error - sign overpunching works only for EBCDIC. We will add the support to ASCII as well shortly

**Comment by Loganhex2021** [comment]
Thanks @yruslan

**Comment by Loganhex2021** [comment]
Sure, I will check and let you know

**Comment by Loganhex2021** [comment]
It's working @yruslan . Thank You!
