### ISSUE TITLE
Testcases are getting failed in windows machine

### ISSUE THREAD

**Issue by codealways** [AbsaOSS/cobrix#465]
## Background [Optional]
Not able to run few testcases

## Question
Few testcases under Test2RecordOffsetsSpec test class are failed due to below error in windows. Its happening with the latest branch. I set up the required winutil and hadoop dll also. But as we are only reading in this testcase it should not expect winutil also.

exception or error caused a run to abort: org.apache.hadoop.io.nativeio.NativeIO$POSIX.stat(Ljava/lang/String;)Lorg/apache/hadoop/io/nativeio/NativeIO$POSIX$Stat; 
java.lang.UnsatisfiedLinkError: org.apache.hadoop.io.nativeio.NativeIO$POSIX.stat(Ljava/lang/String;)Lorg/apache/hadoop/io/nativeio/NativeIO$POSIX$Stat;
	at org.apache.hadoop.io.nativeio.NativeIO$POSIX.stat(Native Method)
	at org.apache.hadoop.io.nativeio.NativeIO$POSIX.getStat(NativeIO.java:608)

**Comment by codealways** [comment]
Any prerequisite required to run on windows or mac in local

**Comment by codealways** [comment]
It was version compatibility issue. After copying hadoop dll version 3.2.2 it worked. 

As part of read me can we update a section <<How to run in local>> so that it will help everyone.

**Comment by yruslan** [comment]
Thanks for this report! We will update `Troubleshooting` section of README with this new info.
