### ISSUE TITLE
SPACE values are converted to 1077952576

### ISSUE THREAD

**Issue by Loganhex2021** [AbsaOSS/cobrix#495]
## Describe the bug
Space ebcdic value is converted to 1077952576 when the data type is 'PIC S9(9) COMP'

## Expected behavior
Expecting null when its an space. note: We disabled the default_trimming_policy

## Copybook (if possible)
```
         01  RECORD.
           05  FIELD1    PIC S9(4) USAGE COMP.
```

Attach a small data file that can help reproduce the issue, if possible.
Hex value is 40404040. The equivalent ebcdic value giving decimal value whereas it supposed to be empty / null

@yruslan could you help me on this

**Comment by yruslan** [comment]
This is as expected according to `USAGE COMP.`

Could you run with `.option("debug", "true")` and send an example of a valid parsed field and invalid parsed field (HEX values generated by the debug option)?
