### ISSUE TITLE
Found duplicate column(s) error when we have 2 same parent nodes with different child nodes

### ISSUE THREAD

**Issue by anu17011993** [AbsaOSS/cobrix#498]
## Bug
We have a copybook which has 2 parent nodes with the same names but the child nodes within the parent have different names.
When I try to read a file using this copybook I get the following error.
**Found duplicate column(s) in the data schema**

## Copybook
```
         01  CARD-CUST.
               15  FIELD1.
                     20  CCD3-IP-STAT          PIC S9(4).
                     20  CCD3-IP-EEFDATE          PIC X(8).
               15  FIELD1.
                     20  CCD4-IP-STAT          PIC S9(4).
                     20  CCD4-IP-EEFDATE          PIC X(8).
```

This copybook and code was working fine last checked(Jul-21) But now when we try to read the same copybook we are getting the above mentioned error.
Has there been a library update which is causing the issue.

**Comment by yruslan** [comment]
It seems `FIELD1` is duplicated. This is Spark restriction, you cannot have 2 columns with the same name.
The only way to fix it would be renaming one of columns, say, to `FIELD2`

**Comment by anu17011993** [comment]
Ya, but it has different child names. Will it still cause an issue?

**Comment by yruslan** [comment]
Yes. If parent fields were different, child records can be the same.

You can workaround like this in your case:
```
         01  CARD-CUST.
                     20  FIELD1-CCD3-IP-STAT             PIC S9(4).
                     20  FIELD1-CCD3-IP-EEFDATE          PIC X(8).
                     20  FIELD1-CCD4-IP-STAT             PIC S9(4).
                     20  FIELD1-CCD4-IP-EEFDATE          PIC X(8).
```

**Comment by anu17011993** [comment]
Thanks @yruslan .Like you said might be a Spark restriction.
2 parent nodes with the same names but the child nodes within the parent having different names seems to be working with Spark3.0.1-Spark3.0.3 
but with Spark.3.1.1 to Spark3.2. we are getting the found duplicate column error.
