### ISSUE TITLE
PIC 9(06) type is ignoring the space (hex: 40).

### ISSUE THREAD

**Issue by Loganhex2021** [AbsaOSS/cobrix#499]
## Describe the bug
The Datatype for a field is PIC(06). The hex value is 'F940F0F0F0F0'. The equivalent value is supposed to be '9 0000'. But while reading the file itself cobrix ignoring space and giving '90000'. 

## Code snippet that caused the issue

```
  spark.read
   .format("cobol")
```

## Copybook (if possible)
```
         01  RECORD.
           05  FIELD1    PIC 9(06).
```

Read_options:
{'encoding': 'EBCDIC', 'ebcdic_code_page': 'cp037', 'string_trimming_policy': 'none', 'debug_ignore_file_size': 'true'}

Could you please confirm the behaviour of cobrix when we have spaces in PIC 9 fields.?
We've seen other instances where Cobrix ignores trailing white spaces in a similar way. We'd like to understand if these are simply ignored from PIC 9 fields and if there is an option to enforce enable / disable that.

@yruslan

**Comment by yruslan** [comment]
Cobrix converts COBOL numeric fields to Spark numeric types (e.g. int, long, double etc). Spark numeric types do not have a notion of spaces between numbers since they are stored in binary representation. If you want to retain spaces in numbers you should use `A(06)`  or `X(06)` as the PIC.

**Comment by Loganhex2021** [comment]
@yruslan 
One more scenario, 
Datatype: PIC 9(02)V9(02)
Hex: 40404040

Since it is repetitive of 40(space), we are expecting null. But cobrix converting this to 0.00

How can we achieve the above result ?

**Comment by yruslan** [comment]
Will check the behavior for all spaces. Meanwhile, could I ask you to make the above scenario a separate issue?

**Comment by yruslan** [comment]
The null detection should be fixed at the master branch now. You can compile it from the source and reference '2.5.0-SNAPSHOT'. Let me know if it fixed the issue for you.
