### ISSUE TITLE
Parse multi segmented file with two segment columns

### ISSUE THREAD

**Issue by sree018** [AbsaOSS/cobrix#507]
Hi @yruslan

I have multi segmented binary file and able to parse it, if single segment column present. How do I parse multi segmented file with two segment columns present ?

ex: copybook

       01 MASTER-DATA.
          05 KEY-TYPE  PIC X(01).
          05 KEY-IND     PIC X(01).
       * KEY=A AND IND=0
          05 KEY-A0-REC.
                 10 DATA-FIELDS  PIC X(998).
       *KEY =B AND IND=0
          05 KEY-B0-REC REDEFINES KEY-A0-REC.
                 10 DATA-FIELDS PIC X(998).
       *KEY= 'A'-'F' AND IND=1
           05 KEY-01-REC REDEFINES KEY-B0-REC.
                 10 DATA-FIELDS PIC X(998).
      * KEY = 'A-F' AND IND=2
          05 KEY-02-REC REDEFINES KEY-01-REC.
                 10 DATA-FIELDS PIC X(998).

**Comment by yruslan** [comment]
If there is no column that can be used as a segment distinguisher a the only way to do it is apply the same custom logic that is used on the mainframe to distinguish these segments.
```scala
val df = spark.read.format("cobol")...

val df2 = df.select(
  $"KEY_TYPE",
  $"KEY-IND",
  when($"KEY_TYPE" === lit("A") && $"KEY_IND" === lit("0"), $"KEY_A0_REC").otherwise(null),
  when($"KEY_TYPE" === lit("B") && $"KEY_IND" === lit("0"), $"KEY_B0_REC").otherwise(null),
  ...
)
```
