### ISSUE TITLE
REPLACE DEFAULT VALUE

### ISSUE THREAD

**Issue by sree018** [AbsaOSS/cobrix#508]
Hi @yruslan 

copybook looks like below
          
    01 DATA-MASTER.
         02 RECORD-KEY    PIC X(03).
         02 REC-XFER-REASON PIC X(07).
         02. REC-VALUE  PIC 9(05) COMP-3 VALUE 0.
       
Incase of REC-VALUE is null, then how to do I replace value 0 ?

**Comment by yruslan** [comment]
Hi, just to clarify. Do you want to replace nulls with zeros or the other way around?

**Comment by sree018** [comment]
Fill values in case of nulls which specified in copybook

**Comment by yruslan** [comment]
You can post-process dataframes you get from Cobrix in this way:
```scala
val df = spark.read.format("cobol")...

// Replaces nulls in REC_VALUE with zeros
val df2 = df.withColumn("REC_VALUE", coalesce($"REC-VALUE", lit(0))
```
