### ISSUE TITLE
copybook with - in field names

### ISSUE THREAD

**Issue by archanasuhani** [AbsaOSS/cobrix#509]
## Background [Optional]
If copybook contains fields with '-' , they convert to an '_'  in the columns name of the table.
Example if copybook has a field as :  MUL-TITLE-PFX-TX
Once the data file is read and we check the schema , the column name comes as: MUL_TITLE_PFX_TX

## Question
As per  the example - https://github.com/AbsaOSS/cobrix , the '-' gets converted to '_' , Why can we not have '-' in the field and column names?

**Comment by yruslan** [comment]
Thanks for the question. This is the feature to make column names more names less confusing. When you use a column name like 'MUL-TITLE' in a SQL query (`SELECT MUL-TITLE FROM TABLE1`), the query parser can't distinguish between '-' being part of the column name or a minus operator.  `SELECT MUL_TITLE FROM TABLE1` is not ambiguiuos.

Spark has an extension, that uses backticks for column names like this, so you can do 'SELECT \`MUL-TITLE\` FROM TABLE1', but it is more complicated and might not work in other systems.

**Comment by archanasuhani** [comment]
Thanks for the clarification !!
