### ISSUE TITLE
RDW headers should never be zero (0,0,0,0)

### ISSUE THREAD

**Issue by Subbu-absa** [AbsaOSS/cobrix#527]
## Background [Optional]
Hi, I am trying to parse and write a data file to a parquet file using latest cobrix. I end up with the following error : RDW headers should never be zero (0,0,0,0).
I added the below configuration 
dfTmp = spark
      .read
      .format("za.co.absa.cobrix.spark.cobol.source")
      .format("cobol")
      .option("copybook", copybookpath)
      .option("encoding","ascii")
      .option("schema_retention_policy", "collapse_root")
      .option("record_format", "V")
      .option("is_rdw_big_endian", "true")
      .load(datafilepath)

## Question
Kindly help me with the right configuration or any changes needed.

**Comment by yruslan** [comment]
Your user name suggests that you are from Absa. Is it so? If yes, please, contact me via the internal chat.

**Comment by Subbu-absa** [comment]
Yes. Will contact you via the teams :) Thanks you
