### ISSUE TITLE
Filler fields are dropped by default.

### ISSUE THREAD

**Issue by swami2018** [AbsaOSS/cobrix#53]
By design the filler fields are dropped. Is there any option to avoid dropping this default behavior ?

**Comment by yruslan** [comment]
Not yet. We have an option to control if you want to drop filler GROUPS. Put for primitive fields all fillers are dropped.

Let's keep this issue open. We can implement a filler retention option.

As a workaround for now you can rename FILLERs to FILLER1, FILLER2, etc.
