### ISSUE TITLE
new code page 1047

### ISSUE THREAD

**Issue by sree018** [AbsaOSS/cobrix#531]
Hi @yruslan 

Can you support  code page 1047 for Latin characters in future releases?

https://zims-en.kiwix.campusafrica.gos.orange.com/wikipedia_en_all_nopic/A/EBCDIC_1047

**Comment by yruslan** [comment]
Hi @sree018, sorry for the delayed response. Yes, we will add the support. Thanks for the documentation! It makes it much easier to do.

**Comment by yruslan** [comment]
@sree018 , this is implemented in the current `master`. Please, check and let me know if it worked for you.

**Comment by yruslan** [comment]
You can build the project from source using sbt: https://github.com/AbsaOSS/cobrix#creating-an-uber-jar

Or wait for new version of Cobrix to be released.
I'd prefer you check it from source first. This way if the change does not work as expected, it would be easier to fix.

**Comment by BenceBenedek** [comment]
Hi @yruslan,

By any chance, could you also include the following 2 byte code pages as well?

https://web.archive.org/web/20141201234940/http://www-01.ibm.com/software/globalization/ccsid/ccsid300.html
https://web.archive.org/web/20141129222534/http://www-01.ibm.com/software/globalization/ccsid/ccsid1364.html
https://web.archive.org/web/20141129205408/http://www-01.ibm.com/software/globalization/ccsid/ccsid1388.html

Many thanks for your help.

Br., Bence.
