### ISSUE TITLE
striping prefix option in column names

### ISSUE THREAD

**Issue by saikumare-a** [AbsaOSS/cobrix#541]
## Background
we have the prefixes in the column names as below

'ABC'-CUST-NAME PIC X.
'ABC'-CUST-ID PIC 9(5).
'ABC'-CUST-PHONE PIC X.
currently, cobrix converting the columns as below

ABC_CUST_NAME
ABC_CUST_ID
ABC_CUST_PHONE

## Feature
can we have the option("strip_column_prefix",list('ABC-','ABC')  which will remove mentioned prefix's if present ,to convert the columns as below

## Example [Optional]
CUST_NAME
CUST_ID
CUST_PHONE

## Benefits
This would help in removing the prefixes which are common for all columns

## Proposed Solution [Optional]
Solution Ideas 
1. checking if column starts with provided prefixes and removing if present

**Comment by yruslan** [comment]
We try to make Cobrix focus on doing one thing well, which is reading and decoding mainframe files. 

Transforming columns according so some pattern is something that Spark is good for already. You can use the above code snippet or similar to achieve the transformation you want, and customize it according to your needs.

Cobrix has already quite steep learning curve. Adding more features that do not serve its main purpose will make it even more difficult to grasp.

**Comment by saikumare-a** [comment]
Hi @yruslan,

Sure and Thank you for your support. you can close this story
