### ISSUE TITLE
data in string format apart from native  target datatype format

### ISSUE THREAD

**Issue by saikumare-a** [AbsaOSS/cobrix#545]
## Background
cobrix converts the data to native type ( decimal, integer etc.,) based on the copybook information.

## Feature
having an option of just dividing the record to columns and having them in string format(as it is , without any trimming) instead of converting to native type would be helpful and provide the below benefits

1) if there is discrepancy between data and copybook , having all columns in string type would help in debugging issues
2) can be helpful to do Data Quality by downstream applications and reports issues (currently invalid data becomes null by spark)

## Example [Optional]
A simple example if applicable.

## Proposed Solution [Optional]
Solution Ideas 
1. one approach could be handling this using option("debug","original")

**Comment by yruslan** [comment]
After thinking about it, the above feature makes sense for ASCII files, but not for EBCDIC.
I see how it could be helpful for ASCII.

**Comment by saikumare-a** [comment]
Thanks for reply and as rightly said, this would be very useful in case of ASCII case.

please provide thoughts on adding this feature (plan and time etc.,) . Thank you for the support

**Comment by yruslan** [comment]
It is hard to say for certain. Maybe end of this year, or Jan next year.

**Comment by yruslan** [comment]
This is done and available in the latest 'master'

**Comment by saikumare-a** [comment]
Hi @yruslan ,

Thanks a lot, i am from python world and no idea about creating the jar file .could you help with steps to create a jar file or attach the jar file to this issue, so that i can test and let you know

**Comment by yruslan** [comment]
Sure. Which Spark and Scala version are you using?

**Comment by saikumare-a** [comment]
currently using the below

groupId: za.co.absa.cobrix
artifactId: spark-cobol_2.12
version: 2.6.1

**Comment by yruslan** [comment]
Here, you can try this one:
[spark-cobol-assembly-2.6.2-SNAPSHOT.zip](https://github.com/AbsaOSS/cobrix/files/10267394/spark-cobol-assembly-2.6.2-SNAPSHOT.zip)

**Comment by saikumare-a** [comment]
Awesome, validated and working as expected. Thanks for the quick turnaround with this enhancement

**Comment by saikumare-a** [comment]
Hi @yruslan,

with option("debug","string"), we see string data in <col_name>_debug fields, how above showing this string data in actual fields instead of <col_name>_debug fields. this would help in showing actual data in actual columns and downstream can take care of handling next step

one option, we can handle this post cobrix by custom code, 
handling in cobrix, might help other cobrix users

**Comment by yruslan** [comment]
So basicaly what you need is to slice ASCII records based on field lengths from a copybook, right?

**Comment by saikumare-a** [comment]
Yes, correct,

is this #25 , already available currently in cobrix?, if yes, please add this info in documentation as i dont see this in documentation

**Comment by yruslan** [comment]
No, it is not implemented yet. But it is the plans to implement it in the future.
