### ISSUE TITLE
option variable_occurs: true not working

### ISSUE THREAD

**Issue by saikumare-a** [AbsaOSS/cobrix#553]
Hi @yruslan,

we are getting different results with 2.6.1 and 2.6.2 snapshot provided in https://github.com/AbsaOSS/cobrix/issues/545

got to see that .option("variable_size_occurs","true") is not working in 2.6.2 snapshot .

all followup columns post variable array are becoming null

in 2.6.2 snapshot,

"D" record_format is still performing index building and giving correct answer
"D2" record_format not performing index building , but giving above mentioned wrong result

please refer https://github.com/AbsaOSS/cobrix/issues/543 for more details

Regards,
Saikumar

**Comment by yruslan** [comment]
Good spot!

Check out the updated jar: 
[spark-cobol-assembly-2.6.2-SNAPSHOT.zip](https://github.com/AbsaOSS/cobrix/files/10308672/spark-cobol-assembly-2.6.2-SNAPSHOT.zip)

**Comment by saikumare-a** [comment]
Hi @yruslan ,

Tested with above updated jar file and both the below issues are fixed.

1) "D" record_format is still performing index building and giving correct answer
  -- now not performing index building and giving correct result
"D2" record_format not performing index building , but giving above mentioned wrong result
  -- now not performing index building and giving correct result

Thank you for the quick reponse.
