### ISSUE TITLE
additional metadata in detailed_metadata option

### ISSUE THREAD

**Issue by saikumare-a** [AbsaOSS/cobrix#580]
## Background
Thanks for adding PIC info  and other useful information in "detailed_metadata" option in 2.6.3 version in #550 

Hi @yruslan ,

Thank you for the support on this.

tested on 2.6.3 and able to see PIC info as below

copybook = """
01 RECORD.
05 ID PIC S9(1).
05 ID_NUM PIC S9V9 OCCURS 1 TIMES.
05 ID_TXT PIC X(2).
"""

metadata
'{"fields":[{"metadata":{"level":5,"pic":"S9(1)"},"name":"ID","nullable":true,"type":"integer"},{"metadata":{"level":5,"maxElements":1,"minElements":0,"pic":"S9(1)V9(1)"},"name":"ID_NUM","nullable":true,"type":{"containsNull":true,"elementType":"decimal(2,1)","type":"array"}},{"metadata":{"level":5,"maxLength":2,"pic":"X(2)"},"name":"ID_TXT","nullable":true,"type":"string"}],"type":"struct"}'

## Feature
could you also help in adding below metadata. this would help in avoiding parsing PIC info

1.decimal precision
2.decimal scale
3.assumed decimal indicator (Y/N) ( in case of S9V9)
4.startPosition and EndPosition (in case of ascii)

Thank you in advance!!
Regards,
Saikumar

**Comment by yruslan** [comment]
1. Decimal scale and precision - you already have them as part of Spark data type (look at `decimal(2,1)` above, 2 is precision and 1 is scale)
2. Assumed decimal indicator, you can derive it from PIC. `pic.contains('.')`. `9V9` is implicit decimal, `9.9` is explicit decimal.
3. Start and end position - makes sense, will add.

**Comment by saikumare-a** [comment]
i agree that decimal scale , precision and assumed decimal indicator can be derived using some extra parsing. 

i feel this extra parsing can be completely removed by adding (as other corresponding metadata elements ) in cobrix.

**Comment by yruslan** [comment]
Okay, I guess it is still helpful. In case, say, fields with PICs 9(x) are converted to 'integer' type, the precision might be lost:
Adding:
- `offset` - starting position of the filed in the record, `byte_size` - the size of the field in bytes
- `precision`, `scale`, `scale_factor` (if not 0)
- `implied_decimal` - if yes, the decimal point is not encoded, but [assumed to be present at the scale position](http://www.3480-3590-data-conversion.com/article-implied-decimal.html#:~:text=Implied%20decimal%20simply%20means%20there,saves%20space%20in%20the%20file.)
- `sign_separate` - if yes the sign is encoded as a separate character (not punched)

**Comment by saikumare-a** [comment]
awesome and thanks . i see these covers all i can think-off.

could you help with elaborating scale_factor?

waiting to use this :)

**Comment by yruslan** [comment]
Scale factor refers to 'P' symbol in PICs: https://github.com/AbsaOSS/cobrix/issues/71

**Comment by saikumare-a** [comment]
Thanks for the info. you are very helpful and thank you for your support.

**Comment by yruslan** [comment]
The features are added, but the option is renamed:
'detailed_metadata' -> 'extended_metadata'.

**Comment by saikumare-a** [comment]
Thank you @yruslan ,

is this available as part of 2.6.3?

**Comment by yruslan** [comment]
It is in latest `master` branch, and the target for 2.6.4

**Comment by saikumare-a** [comment]
validated in 2.6.4 version just now. working as expected

thanks for the support!!
