### ISSUE TITLE
Add support for zoned decimals aka sign operpunching for ASCII data

### ISSUE THREAD

**Issue by saikumare-a** [AbsaOSS/cobrix#591]
## Background [Optional]
we are getting "{"/"}" which indicates the positive/negative value in the zoned decimal columns.

## Question
could you let us know whether cobrix support the zoned decimal data

**for more info on zoned:**
http://www.simotime.com/datazd01.htm

**Comment by saikumare-a** [comment]
this is same and thanks for the information.

**Comment by saikumare-a** [comment]
any copybook example which has zoned decimal data

**Comment by yruslan** [comment]
https://github.com/AbsaOSS/cobrix/blob/f809196ba45522782a2089e8684e74cf81bfe5e7/data/test6_copybook.cob#L46-L46

**Comment by saikumare-a** [comment]
Thanks for the info. 

do we need to set any extra option while reading zoned decimal data for an ASCII format file apart from below?
.option("record_format","D2")
.option("encoding","ascii")

**Comment by yruslan** [comment]
Hi,

I see now what you mean. Zoned decimals or sign overpunching is not supported for ASCII encodings, only for EBCDIC.

Adding this to the backlog.

**Comment by yruslan** [comment]
Hi, @saikumare-a , sorry it seems I was wrong. Cobrix does support ASCII sign overpunch for signed numbers out of the box. No special option needed. Do you have issues with it? If yes, please send be the output example of a field, and the corresponding output of '_debug' field. To enable debug fields use 'option("debug", "true")'
