### ISSUE TITLE
Add 'record_bytes' field that contains raw data of each input record

### ISSUE THREAD

**Issue by yruslan** [AbsaOSS/cobrix#593]
## Background
Original record bytes used for decoding its fields is useful for validation and audit, as well as writing filtered data back to EBCDIC format.

## Feature
Add the ability to generate 'reaord_bytes' field that contains raw bytes of the decoded record.

## Example
```
.option("generate_record_bytes", "true")
```

**Comment by sfuenteRoot** [comment]
![image](https://github.com/AbsaOSS/cobrix/assets/114859405/7b030411-ab1d-4fc8-9037-2d30ca336b5e)

**Comment by sfuenteRoot** [comment]
We are migrating an ETL process from DataStage to scala using your libraries. The file has fields that are handled as "Raw" and converted with the iconv function to hexadecimal. But we are losing bits and we cannot solve it. They are fields that have packaged bits inside.
![image](https://github.com/AbsaOSS/cobrix/assets/114859405/fc07204b-9367-476d-84d1-d2d5c8c628fb)


We read them as follows
.withColumn("field", hex(col("field")))

**Comment by yruslan** [comment]
Is this feature request relevant to the topic? https://github.com/AbsaOSS/cobrix/issues/624

Please, create a separate issue for the issue you are having and please provide more context.

What do you mean by losing bits. Could you please provide an example?

**Comment by sfuenteRoot** [comment]
Sorry, We create the issue #627.
