### ISSUE TITLE
Support for COMP-3 (packed decimals) 

### ISSUE THREAD

**Issue by jindraratne** [AbsaOSS/cobrix#595]
## Question
@yruslan - Does cobrix support parsing COMP-3 data types? If so what option(s), we need to use when reading the files using cobrix running on Databricks? 

background: We are trying to parse a copybook file that has comp-3 data types. When we tested using cobrix, package was able to parse some of the fields accurately but not the ones with comp-3s. Can you please advise? Thanks in advance for your help!

**Comment by yruslan** [comment]
Yes, Cobrix supports COMP-3, and we have many copybooks that use COMP-3 extensively.

You can use `.option("debug", "true")` to see raw values being decoded in additional '_debug' fields. If you see a sequence of bytes that is not decoded correctly, let us know.

**Comment by rafpyprog** [comment]
@jindraratne could you share the options that worked to parse the COMP3s ?
