### ISSUE TITLE
Generating the 5 dependency jars to run cobrix

### ISSUE THREAD

**Issue by elhadi412** [AbsaOSS/cobrix#633]
## Background [Optional]
Hi, I am working on deploying cobrix on AWS Glue job. I need the jar dependencies for running it. I saw on the github readme that there are 5 dependency jars: spark-cobol_2.12-2.6.8.jar, cobol-parser_2.12-2.6.8.jar, scodec-core_2.12-1.10.3.jar, scodec-bits_2.12-1.1.4.jar, and antlr4-runtime-4.8.jar. I am struggling on how I can get these jars. Do I just do a `mvn clean package` or something?

## Question
How can I generate the 5 jars above so I can run cobrix on python in AWS Glue? Using Scala is not an option for us

**Comment by yruslan** [comment]
You can build all dependencies into a fat jar using 'sbt assembly' as described in README.

You can download pre-build fat jsrs from the this page:

**Comment by elhadi412** [comment]
Awesome, thanks @yruslan. Will give that a try.

**Comment by elhadi412** [comment]
Awesome, thanks @yruslan. Will give that a try.
