### ISSUE TITLE
Df to sas7bdat file writer 

### ISSUE THREAD

**Issue by sree018** [AbsaOSS/cobrix#640]
## Background
Currently, ebcdic to csv file and csv file to sas7bdat.

## Feature
Can we directly write ebcdic file to sas7bdat format?

**Comment by yruslan** [comment]
Yes, if there is a Spark writer for 'sas7bdat'.

**Comment by sree018** [comment]
I don’t find any file writer for sas7bdat

**Comment by yruslan** [comment]
Cobrix is a project just for reading mainframe files as Spark dataframes, and can't help with writing data files, sorry.
