### ISSUE TITLE
File start/end offset issue #601

### ISSUE THREAD

**Issue by sree018** [AbsaOSS/cobrix#643]
Hi @yruslan 

Issue :601

Same bug Repeated in 2.6.8 version also.

Can you please help on this ?

**Comment by yruslan** [comment]
Hi,

#601 is already fixed, so your case is likely to be different. Which options are you using and which error are you getting?

**Comment by sree018** [comment]
![20231009_085611](https://github.com/AbsaOSS/cobrix/assets/28417726/768c72e1-cd6f-426e-afa7-517063d8e43c)
![20231009_085234](https://github.com/AbsaOSS/cobrix/assets/28417726/e416bb8d-d47d-4165-b54e-ddde454cc2f1)

**Comment by yruslan** [comment]
Looking at the first snapshot (without file offsets) the processing is working correctly, right?

**Comment by sree018** [comment]
Without file start/end offset options, working fine
