### ISSUE TITLE
0.4.1 SBT import library is huge

### ISSUE THREAD

**Issue by swami2018** [AbsaOSS/cobrix#65]
We tried importing 0.4.1 through the SBT import. The older version (0.4.0) JAR size was approx 12 MB but the current version size is 110 MB. I just want to understand if this is normal or if there are any issues with the project build.

**Comment by yruslan** [comment]
Good spot, thanks! Yes, Spark dependencies are normally have `provided` scope. We sometimes switch the scope to `compile` for debugging. But in 0.4.1 we forgot to revert this debug scope switch.

We will release 0.4.2 soon, probably early next week. This will be fixed there.

**Comment by yruslan** [comment]
Actually we are going to release 0.4.2 today
