### ISSUE TITLE
EBCDIC byte reader -New feature

### ISSUE THREAD

**Issue by swami2018** [AbsaOSS/cobrix#67]
Hi Team - We have a enhancement requirement to read bytes of data from a single EBCDIC file. This file contains different record types and we have a 3 letter keyword or 1 letter to identify the record type. Based on that the file split should happen. 
Note: Its not a standard file which have a RDW.

**Comment by yruslan** [comment]
Please, attach a small (10-15 Kb) example data file and the corresponding copybook. We will take a look,

**Comment by swami2018** [comment]
the tricky part is there is no Cobol copybook for the full file. We have copybook for each record type and unfortunately we can't share the file or copybook.

**Comment by yruslan** [comment]
Several copybooks for each record type is fine. The way Cobrix works you are going to need to combine several copybooks into one such as each record type redefines the others using REDEFINES keyword. A video from our DataWorks'2019 presentation will be available on youtube soon. It shows how you can combine copybooks. We can assist you with this as well.

Still, we need an example to implement what you ask. It may not be a production data file / copybook. It can be a generated or obfuscated synthetic example that has the same structure, e.g. several record types and no RDW headers. We need to understand how these 3 letter and 1 letter keywords are used to determine record sizes.

**Comment by swami2018** [comment]
If we can combine multiple copybooks to one then that solves the problem.
The file looks like the below.
H00..................
R01...................
R05...................
T00...................

Each record type have a fixed length. H00 have a length of 100 and R01 have a length of 3000 etc. Each record type have a copybook and we have option to combine that is great.

**Comment by yruslan** [comment]
It is more clear now. Are there any separators between records, e.g. new lines, or the file is pure binary?

Still, if you can provide us with a sample file, it will make our job a lot easier and you can get the feature faster.

**Comment by swami2018** [comment]
no there are no separator and the file is pure binary.

**Comment by swami2018** [comment]
Just checking if this DataWorks'2019 presentation video is posted online.

**Comment by yruslan** [comment]
Not yet. We are checking it regularly. Will post a link here when the video is available.

**Comment by yruslan** [comment]
Here are Cobrix videos:

DataWorks:
https://youtu.be/o_up7X3ZL24

Spark Summit:
https://youtu.be/BOBIdGf3Tm0

(Will be put to the README page shortly)

**Comment by yruslan** [comment]
This could be solved using custom record header parsers introduced in #68. We will have a PR for it soon.
