### ISSUE TITLE
How to read a pipe separated file with Cobrix

### ISSUE THREAD

**Issue by pinakigit** [AbsaOSS/cobrix#677]
I have a file in Mainframe which is pipe delimited and has a header with column names which are pipe separated too. The file length is Fixed length and after the last field all are filled with spaces.

I can ftp this file as ASCII as well as Binary from Mainframe. Is there a way to read this file in Cobrix as it doesn't have a copybook and  there is no field length for the fields.

**Comment by yruslan** [comment]
Hi, could you send an example of such a file with a copybook? It seems odd that the file is both pipe-separated and fixed record length.

**Comment by pinakigit** [comment]
Sample below. Here every record is of length of 228

Index|Customer Id|First Name|Last Name|Company|City|Country|Phone 1|Phone 2|Email|Subscription Date|Website                                                                                                                           
1|DD37Cf93aecA6Dc|Sheryl|Baxter|Rasmussen Group|East Leonard|Chile|229.077.5154|397.884.0519x718|zunigavanessa@smith.info|2020-08-24|http://www.stephenson.com/                                                                    
2|1Ef7b82A4CAAD10|Preston|Lozano|Vega-Gentry|East Jimmychester|Djibouti|5153435776|686-620-1820x944|vmata@colon.com|2021-04-23|http://www.hobbs.com/                                                                               
3|6F94879bDAfE5a6|Roy|Berry|Murillo-Perry|Isabelborough|Antigua and Barbuda|+1-539-402-0259|(496)978-3969x58947|beckycarr@hogan.com|2020-03-25|http://www.lawrence.com/

**Comment by yruslan** [comment]
The file format looks like a pipe-delimited CSV. You can use `spark-csv` to convert it into a DataFrame: https://spark.apache.org/docs/latest/sql-data-sources-csv.html

```scala
val df = spark.read
  .format("csv")
  .option("header", "true")
  .option("delimiter", "|")
  .option("inferSchema", "true")
  .load("/path/to/file/or/folder")

df.show()
```

**Comment by pinakigit** [comment]
Not sure if I am clear but my requirement is to transfer a VB file from Mainframe in Binary mode (Each record will have different lenght, Number of fields are same but the the field length in different records differ which makes the file variable). I can transmit the file as ASCII and read but we don't want to do that due to checksum issues. We are loking for a solution where we can transmit the file as binary and then read the pipe delimited  file without the copybook as we can read an ASCII File as we can't have a copybook
