### ISSUE TITLE
Metadata copying method does not retain existing metadata

### ISSUE THREAD

**Issue by yruslan** [AbsaOSS/cobrix#697]
## Describe the bug
This method should not replace the metadata, but merge metadata from 2 schemas:
```scala
val schemaMerged = SparkUtils.copyMetadata(schemaFrom, schemaTo)
```

## Code snippet that caused the issue
--

## Expected behavior
Metadata copying method should retain existing metadata.

## Context
--

## Copybook (if possible)
--

**Comment by saikumare-a** [comment]
is it possible to share use this method using pyspark?

**Comment by yruslan** [comment]
Yes, see the PySpark example: https://github.com/AbsaOSS/cobrix/tree/v2.7.4?tab=readme-ov-file#flattening-schema-with-groups-and-occurs

**Comment by saikumare-a** [comment]
Thank you . This helps
