### ISSUE TITLE
SV9(x) should be a valid PIC

### ISSUE THREAD

**Issue by tr11** [AbsaOSS/cobrix#70]
Great library! Hit an issue with a copybook with a `SV9(5)` pic.  The tests seem to indicate this is invalid, but PICs such as `SV9(x)` and `SV99` should be valid.

According to [this](https://www.ibm.com/support/knowledgecenter/en/SSEPEK_11.0.0/apsg/src/tpc/db2z_equivalentcoboldatatypes.html), given a PIC `S9(p-s)V9(s)`:

`p is precision; s is scale. 0≤s≤p≤31. If s=0, use S9(p)V or S9(p). If s=p, use SV9(s). `

**Comment by yruslan** [comment]
Great, thanks, for the bug report! I think we can fix this rather quickly.

**Comment by tr11** [comment]
Fixed by 7d6ff530a8c40fd2c81a025ed0aa714f6d17ef7b
