### ISSUE TITLE
Spaces getting trimmed in Cobrix

### ISSUE THREAD

**Issue by pinakigit** [AbsaOSS/cobrix#708]
## Background [Optional]
We have a column in MF, which have Leading and Trimming and Spaces as well as All Character Spaces. Seems Cobrix is trimming the Spaces

## Question
Is their way I can retin the Spaces? Isee in a thread that mentions the below 2 options. 

.option("improved_null_detection", "false")
so that empty strings won't be treated as nulls, and

.option("string_trimming_policy", "none")

Will any of these options work for me or is there any other option to retain the spaces. Also which Saces Cobrix trims? Leading, Trailing or both?

**Comment by yruslan** [comment]
Yes, 

```
.option("string_trimming_policy", "none")
```

should make Cobrix not trim spaces

**Comment by pinakigit** [comment]
Thanks

**Comment by pinakigit** [comment]
Thanks
