### ISSUE TITLE
Support for decimal scaling

### ISSUE THREAD

**Issue by tr11** [AbsaOSS/cobrix#71]
I have the following PIC on a copybook: `SVPP9(5)`, which is not recognized as a valid PIC. This means that the SV9(5) field will be scaled down by 100.  It seems that we can have fields such as S9(n)P(m) or 9(n)P(m) for scaling up and P(m)9(n) or SVP(m)9(n) for scaling down.

Page 211 on [this](https://www.informatik.uni-leipzig.de/cs/Literature/Textbooks/Cobol/LangRefzOS.pdf) manual gives the following example:

```
PPP999: 0 through .000999
S999PPP: -1000 through -999000 and +1000 through +999000 or zero
```

**Comment by yruslan** [comment]
Thanks! Definitely we need to support this.
