### ISSUE TITLE
Retain Group data

### ISSUE THREAD

**Issue by tr11** [AbsaOSS/cobrix#80]
I have a few copybooks that contain the structure in the copybook below:

```
***********************************************************************
        05  NAME.
            10  SHORT-NAME.
                11  NAME-CHAR-1     PIC X.
                11  FILLER          PIC X(9).
            10  FILLER              PIC X(20).
***********************************************************************
```

The `NAME` field is 30 characters, but the copybook also uses the first 10 chars for the `SHORT-NAME` field and the first character as another field. 

Right now we drop all the information in the `FILLER` fields, so we end up with only the first character in the copybook above. This is connected to #53 and a solution for that one would probably be OK for this case.

Maybe we could add an option to specify non-terminal items to retain? In the example above, we would want to retain `NAME` and `SHORT-NAME`.  We could add an `_NT` suffix or pass in a map allowing to specify the new names.

**Comment by yruslan** [comment]
Yes, we have received similar requests to keep non-terminal fields as a separate field containing concatenations of all its children.
Not sure if we can do this in all cases (e.g. deep levels of nesting, different datatypes), but if all children of a field are strings ('X' or 'A'), it is always doable. So we are going to start with this simple case.

**Comment by tr11** [comment]
Makes sense. The way I handled this in the past on a custom parser was to just read any non-terminal as a `PIC X(n)` where `n` is the size of the children fields.

**Comment by yruslan** [comment]
This is a good idea. Will do the same with a restriction on groups fields that contain only strings.

**Comment by tr11** [comment]
Could we relax that restriction for groups that contain only displayed non-packed items? Something along the lines of:

```
***********************************************************************
        05  ACCOUNT-NO.
            10  FIRST-6       PIC 9(6).
            10  FILLER        PIC 9(6).
            10  LAST-4        PIC 9(4).
***********************************************************************
```

Ideally we'd be able to extract the `ACCOUNT-NO` as a string.  This is not a priority at all -- I can change my copybook to name that filler field in the meantime.

**Comment by yruslan** [comment]
Agreed. Any string types and `DISPLAY` numbers can be used for concatenation.

**Comment by tr11** [comment]
A possible easy solution for this issue could be to add a fake REDEFINES after the group with the size reported from the children elements.  For the example above, 

```
***********************************************************************
        05  ACCOUNT-NO.
            10  FIRST-6       PIC 9(6).
            10  FILLER        PIC 9(6).
            10  LAST-4        PIC 9(4).
        05  ACCOUNT-NO-GROUP  REDEFINES ACCOUNT-NO  PIC X(16).
***********************************************************************
```

**Comment by yruslan** [comment]
Yeah, it might be an easy solution. The only small caveat I see is that the virtual fields will be visible in layout description of the schema. But probably it is a good thing. So likely we'll go with this approach. Thanks for the tip!

**Comment by tr11** [comment]
The PR adds an option to specify non-terminals but automatically assigns by appending "_NT" to the name. Should we pass a Map to the `non_terminals` parameter so we can have a custom name instead?

**Comment by yruslan** [comment]
So far I think a fixed postfix is sufficient. If we have a use case in the future when it needs to be customized, we can always do it later.
