### ISSUE TITLE
OCCURS depending on non-integer fields

### ISSUE THREAD

**Issue by tr11** [AbsaOSS/cobrix#81]
The `OCCURS` clause handler currently enforces an integer `DEPENDING ON` field, which can lead to issues when the field depended on is interpreted as a decimal.  For example, `S9V` is a Decimal(1,0) but in reality is an integer value since it doesn't specify any decimal places.

Maybe we can allow a Decimal(n,0) to be depended on or, alternatively, interpret those as int values.

This is not a priority since one can easily change a copybook `DEPENDING ON` fields to strip the extra `V` decimal place indicator.

**Comment by yruslan** [comment]
Yes, this makes sense.
