### ISSUE TITLE
Allow to specify several copybooks

### ISSUE THREAD

**Issue by yruslan** [AbsaOSS/cobrix#92]
# Background

Multisegment data files, especially ones that come from hierarchical databases are often described by several copybooks. In this case each copybook describes a particular segment.

Currently in order to load multisegment files one must combine segment copybooks in a way that each segment is represented by a GROUP in the copybook, and these segment GROUPs must redefine each other. This is a manual copybook-intrusive work. 

# Feature

Allow Cobrix to accept several copybooks as an input and automatically combine them by placing segments into GROUPs that redefine each other.

**Comment by tr11** [comment]
Closed by #91.
