### ISSUE TITLE
Q: Maturity of this library

### ISSUE THREAD

**Issue by NiallBunting** [AbsaOSS/cobrix#93]
I apologise as I know this the wrong place as it's not an issue, if you could point me to a better place to ask this question I'm happy to go elsewhere.

Anyway, we are wondering what usage this library is getting in production environments, as we just want to confirm the project is mature enough for our usage.

Is it possible to confirm if Absa is using this in prod?

**Comment by yruslan** [comment]
Yes, it is used in ABSA in production.

We see the status of the library as MVP. In additional to unit and integration tests in the open repository we have integration tests on our company's data that we do on premises.

**Comment by xuesteven** [comment]
It works now, thank you yruslan!
