### ISSUE TITLE
Spark-Cobol-App 

### ISSUE THREAD

**Issue by leysajimena** [AbsaOSS/cobrix#94]
I get an error when I execute the command : mvn test  in the example Spark-Cobol-App.
The error is :
java.lang.IllegalStateException: Root segment SEGMENT_ID=='C' not found in the data file.

**Comment by yruslan** [comment]
Good spot! The values of the segment field was something like "SL001", and later changed to be more meaningful. But the binary file remained.

This is fixed in `master`.
