### ISSUE TITLE
Unable to read local file

### ISSUE THREAD

**Issue by hadoopdk** [AbsaOSS/cobrix#97]
whenever I try to read local file, it still search file in hdfs and gives below exception

java.lang.IllegalArgumentException: Wrong FS: file://xxxxxx:9000/root/abc.cpy expected: hdfs://xxxxxx:9000

command:
val df = spark.read.format("cobol").option("encoding", "ebcdic").option("generate_record_id", true).option("copybook", "file:///root/abc.cpy").load("file:///root/data.bin")

**Comment by yruslan** [comment]
Hi, The 'file://' is supported only for copybook locations, not for data files location. We rely heavily on Spark's API for reading the actual binary files and I'm not sure if reading local data files can be supported at all in Spark.
