### ISSUE TITLE
cannot find columns with occurs x times 

### ISSUE THREAD

**Issue by xuesteven** [AbsaOSS/cobrix#98]
When I tried to read the cobol binary file using the following script: 
val df = spark.read.format("za.co.absa.cobrix.spark.cobol.source").option("copybook", "file:///test/XYZ.txt").option("is_record_sequence", "true").option("is_rdw_big_endian", "true").option("schema_retention_policy", "collapse_root").load("/test/test1")

The script ran successfully, but when I retrieve the data, I found the Filler column missing, but other columns are good. In copybook it looks like:
02 FILLER                       OCCURS 2 TIMES
                                      PIC X.

Can you tell me how to solve the issue?

**Comment by yruslan** [comment]
Hi, yes, all FILLER columns are not extracted. We plan to add an option to extract all fillers, but now as a workaround, you can change the FILLER to a different name, say, FILLER1.

**Comment by yruslan** [comment]
It works now, confirmed in a different thread. Closing the issue.
